### PR TITLE
chromium: update to 84.0.4147.125

### LINKED ISSUE #404: chromium: update to 84.0.4147.125
Stable release announcements since our latest update:
https://chromereleases.googleblog.com/2020/08/stable-channel-update-for-desktop.html

Targets and platforms we need to check:

**chromium-x11:**
- [ ] zeus, clang, MACHINE="intel-core2-32"
- [ ] zeus, clang, MACHINE="intel-corei7-64"
- [ ] zeus, clang, MACHINE="raspberrypi3"
- [ ] dunfell, MACHINE="raspberrypi3"

**chromium-ozone-wayland:**

- [ ] zeus, clang, MACHINE="m3ulcb"
- [ ] zeus, clang, MACHINE="qemuarm64"
- [ ] dunfell, clang, MACHINE="raspberrypi3"
- [ ] dunfell, clang, MACHINE="m3ulcb"

### PR DESCRIPTION
**Pull request by msisov**
Stable release announcements since our latest update:
https://chromereleases.googleblog.com/2020/08/stable-channel-update-for-desktop.html

Test-built with:

* chromium-x11
  * zeus, MACHINE="intel-core2-32"
  * zeus, MACHINE="intel-corei7-64"
  * zeus, MACHINE="raspberrypi3"
  * dunfell, MACHINE="raspberrypi3"

* chromium-ozone-wayland:
  * zeus, MACHINE="qemuarm64"
  * zeus, MACHINE="m3ulcb"
  * dunfell, MACHINE="raspberrypi3"
  * dunfell, MACHINE="m3ulcb"

Fixes #404

### CODE REVIEW

**Review by rakuco — COMMENTED** [review]
looks fine to me, but I wonder why the new patch is needed here. did we overlook it before, or did the .105->.125 update introduce a new crash?

**Comment by msisov** [comment]
One of our clients noticed a crash when we updated to M84. I just included this patch into this release instead of doing a separate PR.

**Comment by rakuco** [comment]
I'd rather fix separate things in separate PRs/commits for better tracking of what is doing what. If it isn't too much trouble, could you split those two changes up?

**Comment by msisov** [comment]
done

**Review by rakuco — APPROVED** [review]
thanks!

**Pull request merged**
