### PR TITLE
chromium: update to 115.0.5790.170

### PR DESCRIPTION
**Pull request by MaxIhlenfeldt**
Release notes:
    https://chromereleases.googleblog.com/2023/07/stable-channel-update-for-desktop.html
    https://chromereleases.googleblog.com/2023/07/stable-channel-update-for-desktop_20.html
    https://chromereleases.googleblog.com/2023/07/stable-channel-update-for-desktop_25.html
    https://chromereleases.googleblog.com/2023/08/stable-channel-update-for-desktop.html

Build and patch changes:
------------------------

Drop 0019-Backport-constexpr-std-string-fixes.patch,
0022-Backport-Avoid-capturing-structured-bindings.patch,
0026-Backport-std-string-ends_with-is-C-20.-Use-base-Ends.patch, and
0030-Backport-Avoid-operator-which-is-C-20-specific.patch as they are
included upstream now.

Add one more fix to 0018-Only-default-operator-on-declaration.patch,
which previously was part of
0030-Backport-Avoid-operator-which-is-C-20-specific.patch to prevent a
conflict. Also drop some fixes that are now included upstream.

Drop some fixes from 0021-Add-missing-typename-s.patch that are now
included upstream, and add two new ones.

Add one more fix to 0028-Avoid-capturing-structured-bindings.patch.

Add 0033-Revert-Reland-Reland-mte-refactor-the-tagging-functi.patch to
work around a bug in clang 14 that leads to a build error.

Add 0034-Avoid-parenthesized-initialization-of-aggregates.patch to fix
build errors with clang < 16.

Add 0035-Backport-IWYU-for-chromedriver-chrome-client_hints.h.patch to
fix a build error.

Rebase remaining patches.

License changes:
----------------

Added licenses:
  * third_party/beto-core/LICENSE
  - https://chromium-review.googlesource.com/c/chromium/src/+/4444306

  * third_party/devtools-frontend/src/front_end/third_party/puppeteer-replay/package/LICENSE
  - https://chromium-review.googlesource.com/c/devtools/devtools-frontend/+/4480871

Removed licenses: none.

Updated licenses: none.

Test-built:
-----------

* chromium-ozone-wayland:
 - mickledore, clang, MACHINE=qemuarm64
 - kirkstone, clang,  MACHINE=raspberrypi4-64

* chromium-x11
 - dunfell, clang**,  MACHINE=raspberrypi4-64

** Please note that Chromium requires below set-up when on dunfell
branch.
- The clang version to be >= 14 and for that, use the latest
  meta-clang/dunfell-clang14 branch.
- Require the latest meta-oe with Nodejs 14.x support.
- Add the PREFERRED_VERSION_nodejs-native = "14.%" in conf/local.conf
  file.

Signed-off-by: Max Ihlenfeldt <max@igalia.com>

### CODE REVIEW

**Comment by MaxIhlenfeldt** [comment]
I'll add the detailed description later, maybe you can please start testing already? @nrpt-m

**Comment by nrpt-m** [comment]
> I'll add the detailed description later, maybe you can please start testing already? @nrpt-m

Sure, I am starting the testing.

**Comment by MaxIhlenfeldt** [comment]
Updated the commit message and PR description.

**Comment by nrpt-m** [comment]
@MaxIhlenfeldt 
Have completed the builds & testing in master branch for all these below systems and chromium worked well in all these systems.

- chromium-ozone-wayland: qemux86-64

- chromium-x11: qemux86-64, qemuarm, qemuarm64, raspberrypi4-64

Next, starting with kirkstone, dunfell & mickledore branches.

**Comment by MaxIhlenfeldt** [comment]
Patch 0035-... has been merged upstream as https://crrev.com/c/4767547, so I updated the patch file (+ commit message and PR description) accordingly.

**Comment by san-skov-dk** [comment]
How to get meta-clang/dunfell-clang14 ?

**Comment by MaxIhlenfeldt** [comment]
The `dunfell-clang14` branch is still experimental. Currently, you can find it at https://github.com/rakuco/meta-clang/tree/dunfell-clang14 (i.e. it lives in a fork).

**Comment by MaxIhlenfeldt** [comment]
> The MTE patch is a bit scary, but I guess it's the best we can do at the moment.

Not sure what you mean by scary, but luckily we can drop it once we use clang >= 15 everywhere.

> I just have no idea what to do with the dunfell-clang14 branch :/

Me neither, but we definitely need it for this update. @kraj how do you suggest we proceed with https://github.com/kraj/meta-clang/issues/835?

**Comment by nrpt-m** [comment]
> Next, starting with kirkstone, dunfell & mickledore branches.

@MaxIhlenfeldt Have completed the builds & testing in kirkstone branch for all these below systems and chromium worked well in all these systems.

* chromium-ozone-wayland: qemux86-64
* chromium-x11: qemux86-64, qemuarm, qemuarm64, raspberrypi4-64

Next, starting with dunfell & mickledore branches.

**Comment by nrpt-m** [comment]
@MaxIhlenfeldt ,
I am getting errors while building all the machines in dunfell branch. Have attached the build errors here.
[chromium-115.0.5790.170-dunfell-build-errors.txt](https://github.com/OSSystems/meta-browser/files/12333758/chromium-115.0.5790.170-dunfell-build-errors.txt)

Could you please check these errors.

**Comment by rakuco** [comment]
@nrpt-m Is `PREFERRED_VERSION_nodejs-native = "14.%"` set in `local.conf`? These look like nodejs errors that we used to get in Node 12.

**Comment by nrpt-m** [comment]
> @nrpt-m Is `PREFERRED_VERSION_nodejs-native = "14.%"` set in `local.conf`? These look like nodejs errors that we used to get in Node 12.

Sorry, I missed it "PREFERRED_VERSION_nodejs-native = "14.%".

**Comment by MaxIhlenfeldt** [comment]
FYI, I'll be ooo tomorrow and the rest of the week. I suppose it's a bit optimistic, but should there be progress regarding the `dunfell-clang14` branch that means we can merge this PR, feel free to take this over and merge it without me.

**Comment by nrpt-m** [comment]
> **RPi4/dunfell the "network service crashed" problem is still there. Next is mickledore branch.

@MaxIhlenfeldt & @rakuco 
Have completed the builds & testing in mickledore branch for all these below systems and chromium worked well in all these systems.

- chromium-ozone-wayland: qemux86-64

- chromium-x11: qemux86-64, qemuarm, qemuarm64, raspberrypi4-64

If you are agree with all these above test results then, we are good to go for merge.

**Comment by rakuco** [comment]
Thank you for testing! Everything looks fine from my side too, but we need to figure out the dunfell-clang14 situation first.

**Comment by nrpt-m** [comment]
@rakuco ,
Is there any particular reason for not merging dunfell-clang14 branch yet ? It's been two weeks that we have finished the testing for chromium-115.

**Review by rakuco — APPROVED** [review]
The dunfell-clang14 branch was finally created in meta-clang last Friday, so I'll go ahead and merge this PR while Max is OoO.

**Pull request merged**
