### PR TITLE
chromium: update to 104.0.5112.101

### PR DESCRIPTION
**Pull request by rwmacleod**
Stable channel release notes:
   https://chromereleases.googleblog.com/2022/08/stable-channel-update-for-desktop_16.html

Patches:
--------

Manually update:
   0013-clang-Re-enable-opaque-pointers.patch
to deal with a comment change.

Update the musl mallinfo patch:
   musl/0001-mallinfo-implementation-is-glibc-specific.patch
to deal with a new header file.

Refresh patches to remove fuzz (using devtool).

License changes:
----------------

Note that on dunfell, this warning occurs:
   WARNING: chromium-x11-104.0.5112.101-r0 do_populate_lic: \
      chromium-x11: No generic license file exists for: LGPL-2.0-or-later in any provider
meta-browser doens't have a dunfell specific branch so it seems
that the warning can't be eliminated.

Update the license checksums by running the new generate_license_list.py script added
to this repo by saying yes to all the exception queries using for example:
   $ yes | python3 generate_license_list.py ...

Added licenses:
  * base/third_party/cityhash_v103/COPYING
  - https://chromium-review.googlesource.com/c/chromium/src/+/3412104

  * third_party/android_system_sdk/LICENSE
  - https://chromium-review.googlesource.com/c/angle/angle/+/3251685

  * third_party/blink/LICENSE_FOR_ABOUT_CREDITS
  - https://chromium-review.googlesource.com/c/chromium/src/+/1350011

  * third_party/content_analysis_sdk/LICENSE
  - https://chromium-review.googlesource.com/c/chromium/src/+/3623681

  * third_party/cpuinfo/src/LICENSE
  - https://chromium-review.googlesource.com/c/chromium/src/+/3668676

  * third_party/ipcz/LICENSE
  - https://chromium-review.googlesource.com/c/chromium/src/+/3577818

  * third_party/libaom/source/libaom/LICENSE
  - https://chromium-review.googlesource.com/c/chromium/src/+/726469

  * third_party/libgav1/src/LICENSE
  - https://chromium-review.googlesource.com/c/chromium/src/+/3412106

  * third_party/puffin/LICENSE
  - https://chromium-review.googlesource.com/c/chromium/src/+/3639351

Removed licenses: (none)

Updated licenses: (none)

Test-built:
-----------

* chromium-ozone-wayland:
 - master, clang,    MACHINE=qemux86-64, qemuarm64, qemuarm
 - kirkstone, clang, MACHINE=qemux86-64, qemuarm64, qemuarm
 - dunfell, clang**, MACHINE=qemux86-64, qemuarm64, qemuarm

* chromium-x11
 - master, clang,    MACHINE=qemux86-64, qemuarm64, qemuarm
 - kirkstone, clang, MACHINE=qemux86-64, qemuarm64, qemuarm
 - dunfell, clang**, MACHINE=qemux86-64, qemuarm64, qemuarm

Also built with TCLIBC=musl for qemux86-64 on master.

** Please note that Chromium requires clang version to be >= 12.
For that, when on dunfell branch, use the meta-clang/clang12 branch.

### CODE REVIEW

**Review by msisov — APPROVED** [review]
sorry for delay. lgtm

**Review by rakuco — COMMENTED** [review]
Thank you for working on this! I'm also surprised that no new patches needed to be backported, that's good news!

I find it a bit suspicious that `LIC_FILES_CHKSUM` didn't have to be updated from M103 to M104 though. I've sent #656 with the script I used to use when I updated this recipe myself, I tried it locally and got a few new entries.

**Comment by rwmacleod** [comment]
@rakuco Thanks for checking on that. I thought I just got lucky wrt licenses.

**Comment by rwmacleod** [comment]
I'm not sure what happened here. I was force-pushing license updates to my clone and somehow this PR ended up closed but not updated to 104!

Anyway, I have the update in my clone:
   https://github.com/rwmacleod/meta-browser/commits/master
   https://github.com/rwmacleod/meta-browser/commit/9968536615e10db206144fabe85586f2341a67a9
   

Should I try to re-open this PR (How?) or just create a new PR ?

**Review by rakuco — COMMENTED** [review]
I'm glad you managed to reopen the PR. I think there's just one thing left: the commit/PR message does not mention the new licenses like we usually do (see e.g. commit c94253bcca1409885bf7155c2002d0a842e0a4f8).

I assume you have an upstream Chromium git checkout that you could use for checking these changes; if you don't, I think we'll need to rethink this process to make it easier for people other than @msisov or myself to update the Chromium recipes (maybe just listing the new license files without the accompanying upstream commit that added them, for example).

**Comment by rakuco** [comment]
> Update the license checksums by running the new generate_license_list.py script added
> to this repo but with the interactive exception handling stubbed out to continue on each
> exception:
> #if input('Ignore (y)? ') == 'y':
> continue
> #raise

Side note: you can also invoke it via `yes | python3 generate_license_list.py ...`.

**Comment by rwmacleod** [comment]
> I think there's just one thing left: the commit/PR message does not mention the new licenses like we usually do (see e.g. commit [c94253b](https://github.com/OSSystems/meta-browser/commit/c94253bcca1409885bf7155c2002d0a842e0a4f8)).
> 
> I assume you have an upstream Chromium git checkout that you could use for checking these changes; if you don't, I think we'll need to rethink this process to make it easier for people other than @msisov or myself to update the Chromium recipes (maybe just listing the new license files without the accompanying upstream commit that added them, for example).

I do have a ( 30 GB !! ) clone of the git tree but I've found that since you guys seem to be happy with links to the chromium-review site, for most license changes you can find the related review by searching (top right search box) for the path such as: "base/third_party/cityhash_v103/COPYING"

**Comment by rakuco** [comment]
> I do have a ( 30 GB !! ) clone of the git tree but I've found that since you guys seem to be happy with links to the chromium-review site, for most license changes you can find the related review by searching (top right search box) for the path such as: "base/third_party/cityhash_v103/COPYING"

Thanks, I see you updated the commit message with the Gerrit review URLs. The idea behind having the links in the commit message is to potentially help users should they need to find out more about a given license addition/change/removal without requiring them to have a Chromium checkout.

I'll merge this PR, but can you in the meantime update the pull request message too?

**Review by rakuco — APPROVED** [review]
thanks!

**Comment by rwmacleod** [comment]
> Thanks, I see you updated the commit message with the Gerrit review URLs. The idea behind having the links in the commit message is to potentially help users should they need to find out more about a given license addition/change/removal without requiring them to have a Chromium checkout.
> 
> I'll merge this PR, but can you in the meantime update the pull request message too?

Thanks for explaining and I think I did update the PR message already: https://github.com/OSSystems/meta-browser/pull/654#issue-1348688386

**Pull request merged**
