### PR TITLE
chromium update to 100.0.4896.127

### PR DESCRIPTION
**Pull request by rwmacleod**
chromium: update to 100.0.4896.127
    
    Release notes:
      https://chromereleases.googleblog.com/2022/04/stable-channel-update-for-desktop_14.html
    
    License changes:
    ---------------
    
    No changes.
    
    ---------------
    
    Test-built with:
    
    * chromium-x11
      * master,  clang, MACHINE="qemuarm64,qemux86-64"

### CODE REVIEW

**Review by kraj — COMMENTED** [review]
did you try to apply musl patches and see if they need rebasing ?

**Comment by msisov** [comment]
Started compilation tests.

**Comment by rwmacleod** [comment]
@kraj  As usual, I forgot about musl but I just checked and it's fine with: TCLIBC=musl bitbake chromium-x11

**Comment by msisov** [comment]
@rwmacleod, please add the following information to the commit message -

Test-built with:

chromium-ozone-wayland:
- honister, clang, MACHINE="intel-corei7-64"
- honister, clang, MACHINE="raspberrypi3
- hardknott, clang, MACHINE="raspberrypi3
- dunfell, clang**, MACHINE="qemuarm64"

chromium-x11
- honister, clang, MACHINE="raspberrypi3"
- hardknott, clang, MACHINE="raspberrypi3"
- dunfell, clang**, MACHINE="raspberrypi3"

** Please note that Chromium requires clang version to be >= 12.
For that, when on dunfell branch, use meta-clang/clang12 branch.

**Comment by rwmacleod** [comment]
How do I update the commit log for an existing PR using "gh pr" ?
I'm a newbie with this tool and RTFM / google isn't helping.﻿

**Comment by kraj** [comment]
> How do I update the commit log for an existing PR using "gh pr" ? I'm a newbie with this tool and RTFM / google isn't helping.

its better to edit it in your workspace and then force push to pull branch.

**Comment by rakuco** [comment]
> How do I update the commit log for an existing PR using "gh pr" ?

Like @kraj said, it's better to just use git directly: amend your commit locally, then use `git push --force <your-remote> chromium-update-to-100.0.4896.127`.

**Comment by rwmacleod** [comment]
Done: https://github.com/rwmacleod/meta-browser/commit/a3f82cf8a339bb84af379810b302af8c39866f85

**Review by rakuco — APPROVED** [review]
lgtm. @msisov can you take a look as well?

**Review by msisov — APPROVED** [review]
lgtm

**Pull request merged**
