### PR TITLE
chromium: add support for 32-bit raspberrypi

### PR DESCRIPTION
**Pull request by yangjiel**
Applying the commit from master into morty to support the raspberry pi devices.

### CODE REVIEW

**Comment by otavio** [comment]
@yangjiel @twoerner is this included in master?

**Comment by yangjiel** [comment]
@otavio This commit is from master. https://github.com/OSSystems/meta-browser/commit/c8337557a49204959a54d193a310a358da3c1f8e
Current we are using Morty branch for our Raspberry Pi, it is great that chromium can support raspberry pi machine in Morty branch.
Thank you.

**Comment by twoerner** [comment]
@otavio yes, this is already in master. However, the recipes-browser/chromium/files/armv7ve/include.gypi file in master is different than what is proposed here. Not sure if they should be sync'ed or if the changes are necessary. I haven't had a chance to try this pull request yet.

**Comment by otavio** [comment]
@yangjiel as you seem to be using Chromium actively, could you take a look on this?

**Comment by yangjiel** [comment]
@kraj @otavio But int the `files/armv7ve/include.gypi` flie, it uses `'armv7': 1,` as well. I am not much familiar with these parameters, what I guess is both armv7a and armv7ve are the armv7 series. I have compile a kernel image using the patch I submit here, I will run the chromium and test it shortly.

**Comment by yangjiel** [comment]
Sorry for the delay. I have confirmed the chromium works on Raspberry Pi 3 model B as expected.
Thank you.

**Comment by kraj** [comment]
also with armv7ve ?

**Comment by yangjiel** [comment]
@kraj Sorry, what do you mean by "also with armv7ve"? This patch is for Raspberry Pi devices. Since I only have the Raspberry Pi 3 model B, I am only able to test on it.

**Comment by kraj** [comment]
Look at my review comment earlier on your patch

**Comment by yangjiel** [comment]
You mean I should better to change the armv7 to  armv7ve and test again? I can do that if you want and reply with the result latter. Also notice the file for armv7a is using armv7 as well in morty and master branch.

**Comment by yangjiel** [comment]
I changed some files according your commit https://github.com/OSSystems/meta-browser/commit/f2cd46967a9d76be67fd45d062a1d2fc6a68a055 and tried to compile the chromium-wayland it but filed.
```
| In file included from ../../content/common/gpu/media/va_surface.h:14:0,
|                  from ../../content/common/gpu/media/vaapi_wrapper.h:21,
|                  from ../../content/common/gpu/media/vaapi_video_decode_accelerator.h:26,
|                  from ../../content/common/gpu/media/gpu_video_decode_accelerator.cc:47:
| ../../third_party/libva/va/va.h:83:27: fatal error: va/va_version.h: No such file or directory
|  #include <va/va_version.h>
|                            ^
| compilation terminated.
```
The chromium-wayland is not compiling on armv7ve target.
I didn't see any libva or libva_dev provided. Do you have any idea? Am I missed any other patches or commits?

**Comment by kraj** [comment]
it seems its asking for libva,  which should be added to dependencies, although I  think thats orthogonal problem. Least likely related to -march change thats suggested here.

**Pull request merged**
