### PR TITLE
chromium: Update to 130.0.6723.58

### LINKED ISSUE #841: Update to Chromium 130
Release notes:
* https://chromereleases.googleblog.com/2024/10/stable-channel-update-for-desktop_15.html

### PR DESCRIPTION
**Pull request by MaxIhlenfeldt**
Fixes #841.

Release notes:
    https://chromereleases.googleblog.com/2024/10/stable-channel-update-for-desktop_15.html
    https://chromereleases.googleblog.com/2024/10/stable-channel-update-for-desktop_22.html

Build and patch changes:
------------------------

Add one patch to fix a build error on scarthgap with clang 18.

Rebase remaining patches.

License changes:
----------------

Added licenses:
  * third_party/android_deps/libs/com_google_dagger_hilt_core/LICENSE
  - https://chromium-review.googlesource.com/c/chromium/src/+/5823738

  * third_party/android_deps/libs/com_squareup_okio_okio_jvm/LICENSE, third_party/android_deps/libs/org_jetbrains_kotlinx_kotlinx_serialization_core_jvm/LICENSE
  - https://chromium-review.googlesource.com/c/chromium/src/+/4294685, https://chromium-review.googlesource.com/c/chromium/src/+/5857028

  * third_party/android_deps/libs/jakarta_inject_jakarta_inject_api/LICENSE
  - https://chromium-review.googlesource.com/c/chromium/src/+/5824189

  * third_party/catapult/third_party/pipeline/LICENSE
  - https://chromium-review.googlesource.com/c/catapult/+/5847129

  * third_party/devtools-frontend/src/front_end/third_party/third-party-web/LICENSE
  - https://chromium-review.googlesource.com/c/devtools/devtools-frontend/+/5809617

  * third_party/pdfium/third_party/agg23/copying, third_party/pdfium/third_party/libopenjpeg/LICENSE, third_party/pdfium/third_party/libtiff/LICENSE.md
  - https://pdfium-review.googlesource.com/c/pdfium/+/124210

Removed licenses:
  * courgette/third_party/bsdiff/LICENCE, courgette/third_party/divsufsort/LICENSE
  - https://chromium-review.googlesource.com/c/chromium/src/+/5812826

  * third_party/android_deps/libs/android_arch_core_common/LICENSE, third_party/android_deps/libs/android_arch_core_runtime/LICENSE, third_party/android_deps/libs/android_arch_lifecycle_common/LICENSE, third_party/android_deps/libs/android_arch_lifecycle_livedata/LICENSE, third_party/android_deps/libs/android_arch_lifecycle_livedata_core/LICENSE, third_party/android_deps/libs/android_arch_lifecycle_runtime/LICENSE, third_party/android_deps/libs/android_arch_lifecycle_viewmodel/LICENSE, third_party/android_deps/libs/com_android_support_asynclayoutinflater/LICENSE, third_party/android_deps/libs/com_android_support_collections/LICENSE, third_party/android_deps/libs/com_android_support_coordinatorlayout/LICENSE, third_party/android_deps/libs/com_android_support_cursoradapter/LICENSE, third_party/android_deps/libs/com_android_support_customview/LICENSE, third_party/android_deps/libs/com_android_support_documentfile/LICENSE, third_party/android_deps/libs/com_android_support_drawerlayout/LICENSE, third_party/android_deps/libs/com_android_support_interpolator/LICENSE, third_party/android_deps/libs/com_android_support_loader/LICENSE, third_party/android_deps/libs/com_android_support_localbroadcastmanager/LICENSE, third_party/android_deps/libs/com_android_support_print/LICENSE, third_party/android_deps/libs/com_android_support_slidingpanelayout/LICENSE, third_party/android_deps/libs/com_android_support_support_compat/LICENSE, third_party/android_deps/libs/com_android_support_support_core_ui/LICENSE, third_party/android_deps/libs/com_android_support_support_core_utils/LICENSE, third_party/android_deps/libs/com_android_support_swiperefreshlayout/LICENSE, third_party/android_deps/libs/com_android_support_versionedparcelable/LICENSE, third_party/android_deps/libs/com_android_support_viewpager/LICENSE
  - https://chromium-review.googlesource.com/c/chromium/src/+/5835984

  * third_party/android_toolchain_canary/NOTICE
  - https://chromium-review.googlesource.com/c/chromium/src/+/5798143

  * third_party/bidimapper/licenses/LICENSE.urlpattern_polyfill
  - https://chromium-review.googlesource.com/c/chromium/src/+/5850570

  * third_party/catapult/third_party/requests_toolbelt/LICENSE
  - https://chromium-review.googlesource.com/c/catapult/+/5847130

  * third_party/openscreen/src/third_party/zlib/LICENSE
  - https://chromium-review.googlesource.com/c/openscreen/+/5816482

Updated licenses:
  * chrome/installer/mac/third_party/xz/LICENSE
  - https://chromium-review.googlesource.com/c/chromium/src/+/5846369

  * third_party/ced/LICENSE
  - https://chromium-review.googlesource.com/c/chromium/src/+/5816777

  * third_party/perfetto/LICENSE
  - https://github.com/google/perfetto/commit/fcae37623e3eeaefe7ecbfa192f87f8c44b56ecc

Test-built (big thanks to @SoumyaWind):
---------------------------------------

* chromium-ozone-wayland:
 - master, clang,    MACHINE=qemux86-64
 - scarthgap, clang, MACHINE=qemuarm64, qemux86-64

* chromium-x11:
 - master, clang,    MACHINE=qemuarm, qemuarm64, qemux86-64, raspberrypi4-64
 - scarthgap, clang, MACHINE=qemuarm, qemuarm64, qemux86-64, raspberrypi4-64

### CODE REVIEW

**Comment by MaxIhlenfeldt** [comment]
Wanted to use the latest respin, but the tarball isn't available yet, so I'll send a separate PR to update once this one has been merged.

@SoumyaWind as always, testing would be greatly appreciated!

**Review by rakuco — APPROVED** [review]
lgtm

**Comment by SoumyaWind** [comment]
@MaxIhlenfeldt sure, I will start testing.

**Comment by adalessandro** [comment]
LGTM, successfully built on kirkstone (on top of https://github.com/OSSystems/meta-browser/pull/843). Quickly tested, not much tbh, but overall looks good. Thanks!

**Comment by SoumyaWind** [comment]
@MaxIhlenfeldt, I have completed the testing for below configuration for Poky master with latest changes. Here are the results for your reference:

1. **chromium-x11 on qemux86-64 target**: Compiled successfully without any build issues. Verified chromium version using qemux86-64 emulator
2. **chromium-x11 on qemuarm target**: Without debug configuration, encountered the following error during build -
>| arm-poky-linux-gnueabi-ld.lld: error: output file too large: 6926692460 bytes
>| section sizes:
>| .interp 25
>| .note.ABI-tag 32
>| .note.crashpad.info 28
>| .note.gnu.build-id 36
>| .dynsym 24976
>| .gnu.version 3122
>| .gnu.version_r 1040
>| .gnu.hash 372
>| .dynstr 35193
>| .rel.dyn 7048288
>| .ARM.exidx 8856
>| .rel.plt 11496
>| .rodata 14485117
>| .ARM.extab 13048
>| .eh_frame_hdr 12
>| .eh_frame 4
>| .text 144134188
>| .init 28
>| .fini 8
>| malloc_hook 500
>| .plt 23024
>| .tdata 168
>| .tbss 2980
>| .fini_array 4
>| .init_array 8
>| .data.rel.ro 4839592
>| .dynamic 472
>| .got 54368
>| .got.plt 5760
>| .relro_padding 2208
>| .data 388752
>| .tm_clone_table 0
>| protected_memory 4118
>| protected_memory_buffer 1
>| .bss 1556908
>| .comment 133
>| .ARM.attributes 59
>| .debug_aranges 264
>| .debug_info 3679024842
>| .debug_abbrev 141898144
>| .debug_line 278367881
>| .debug_str 1389867525
>| .debug_line_str 4077999
>| .debug_rnglists 153419870
>| .debug_loclists 328122091
>| .debug_str_offsets 592160212
>| .debug_addr 37817676
>| .debug_frame 22577488
>| .symtab 31552128
>| .shstrtab 586
>| .strtab 96713551
>|
>| arm-poky-linux-gnueabi-clang++: error: linker command failed with exit code 1 (use -v to see invocation)
>| ninja: build stopped: subcommand failed.

With GN configuration - is_debug=true, is_official_build=false, symbol_level=2 and with the dependencies:

DISTRO_FEATURES with usrmerge and systemd
VIRTUAL-RUNTIME_init_manager to systemd
systemd and systemd-dev in IMAGE_INSTALL
The build was successful for qemuarm, and I was able to verify chromium version using qemuarm emulator
3. **chromium-x11 on qemuarm64 target**: Compiled successfully without build issues. Verified chromium version using qemuarm64 emulator
4. **chromium-x11 on raspberrypi4-64 target**: Compiled successfully without any build issues. I could not test on actual hardware due to unavailability.
5. **chromium-ozone-wayland on qemux86-64 target**: Compiled successfully without any build issues, verified chromium version using qemux86-64 emulator

**Comment by SoumyaWind** [comment]
I have completed testing with the following configurations for poky scarthgap with the latest changes. Here are the results for your reference:

1. **chromium-x11 on qemux86-64 target**: Compiled successfully without any build issues, verified chromium version using the qemux86-64 emulator.
2. **chromium-x11 on qemuarm target**: Compiled successfully without any build issues, verified chromium version using the qemuarm emulator.
3. **chromium-x11 on qemuarm64 target**: Compiled successfully without any build issues, verified chromium version using the qemuarm64 emulator.
4. **chromium-x11 on raspberrypi4-64 target**: Compiled successfully without any build issues. I could not test on actual hardware due to unavailability.
5. **chromium-ozone-wayland on qemux86-64 target**: Compiled successfully without any build issues, verified chromium version using the qemux86-64 emulator.

**Comment by MaxIhlenfeldt** [comment]
Thanks!

**Pull request merged**
