### PR TITLE
chromium: Update to 74.0.3729.157.

### PR DESCRIPTION
**Pull request by msisov**
Release announcement:
https://chromereleases.googleblog.com/2019/05/stable-channel-update-for-desktop.html

Test-built with:
 chromium-x11:
 * rocko, GCC 7, MACHINE="qemuarm64"
 * sumo, GCC 7, MACHINE="raspberrypi3"
 * thud, GCC 8, MACHINE="intel-core-i7-64" and MACHINE="intel-core2-32"

 chromium-ozone-wayland:
 * sumo, GCC 7, MACHINE="raspberrypi3"
 * sumo, GCC 7, MACHINE="beaglebone"
 * thud, GCC 8, MACHINE="m3ulcb"
 * thud, clang, MACHINE="qemuarm64"

Signed-off-by: Maksim Sisov <msisov@igalia.com>
Signed-off-by: Raphael Kubo da Costa <raphael.kubo.da.costa@intel.com>

### CODE REVIEW

**Comment by rakuco** [comment]
> Test-built with:
> chromium-x11:
> 
> * rocko, GCC 7, MACHINE=raspberrypi3"
> * sumo, GCC 7, MACHINE="raspberrypi3"
> * thud, GCC 8, MACHINE="intel-core-i7-64" and MACHINE="intel-core2-32"
> 
> chromium-ozone-wayland:
> 
> * sumo, GCC 7, MACHINE="raspberrypi3"
> * sumo, GCC 7, MACHINE="beaglebone"
> * thud, GCC 8, MACHINE="m3ulcb"

I actually tested chromium-ozone-wayland with clang on thud with MACHINE="qemuarm64", and my chromium-x11 test on rocko was with MACHINE="qemuarm64".

**Comment by msisov** [comment]
Thanks. we need to create a separate table with tests done.

I'll do it for the next release.

**Comment by msisov** [comment]
do we need lgtm from @otavio as well?

**Comment by rakuco** [comment]
In this case, I think you can go ahead -- it's a very small diff and we've tested it exhaustively.

**Pull request merged**
