### PR TITLE
chromium: update to 120.0.6099.109

### PR DESCRIPTION
**Pull request by MaxIhlenfeldt**
Release notes:
    https://chromereleases.googleblog.com/2023/12/stable-channel-update-for-desktop.html
    https://chromereleases.googleblog.com/2023/12/stable-channel-update-for-desktop_6.html
    https://chromereleases.googleblog.com/2023/12/stable-channel-update-for-desktop_12.html

Build and patch changes:
------------------------

Drop three backported patches that are included upstream now, and add
four new backports.

Add more fixes to 0013-Add-missing-typename-s.patch.

Rename 0014-Don-t-pass-disable-auto-upgrade-debug-info-to-linker.patch
to 0014-Don-t-pass-unknown-LLVM-options.patch and also disable the
`split-threshold-for-reg-with-hint` option.

Add more fixes to
0017-Avoid-parenthesized-initialization-of-aggregates.patch.

Add more fixes to
0018-Fix-constexpr-variable-cannot-have-non-literal-type-.patch.

Add 0022-Use-base-ranges-instead-of-std-ranges.patch to fix a build
error on older versions of clang (on mickledore, kirkstone, and
dunfell).

Rebase remaining patches.

License changes:
----------------

Added licenses:
  * third_party/devtools-frontend/src/front_end/third_party/csp_evaluator/package/LICENSE
  - https://chromium-review.googlesource.com/c/devtools/devtools-frontend/+/4580488

Removed licenses:
  * third_party/android_deps/libs/com_google_guava_listenablefuture/LICENSE
  - https://chromium-review.googlesource.com/c/chromium/src/+/4960997

  * third_party/xdg_shared_mime_info/LICENSE
  - https://chromium-review.googlesource.com/c/chromium/src/+/4974772

Updated licenses:
  * third_party/dawn/LICENSE
  - https://dawn-review.googlesource.com/c/dawn/+/155561

  * third_party/ffmpeg/CREDITS.chromium
  - https://chromium.googlesource.com/chromium/third_party/ffmpeg.git/+/265b12a2

  * third_party/speech-dispatcher/COPYING => third_party/speech-dispatcher/COPYING.LGPL
  - https://chromium-review.googlesource.com/c/chromium/src/+/4917472

  * third_party/vulkan_memory_allocator/LICENSE.txt
  - https://chromium-review.googlesource.com/c/chromium/src/+/4911597

Test-built (big thanks to @nrpt-m):
-----------------------------------

* chromium-ozone-wayland:
 - master, clang,     MACHINE=qemux86-64
 - nanbield, clang,   MACHINE=qemux86-64
 - mickledore, clang, MACHINE=qemuarm64, qemux86-64
 - kirkstone, clang,  MACHINE=qemux86-64, raspberrypi4-64
 - dunfell, clang**,  MACHINE=qemux86-64

* chromium-x11
 - master, clang,     MACHINE=qemux86-64, qemuarm, qemuarm64, raspberrypi4-64
 - nanbield, clang,   MACHINE=qemux86-64, qemuarm, qemuarm64, raspberrypi4-64
 - mickledore, clang, MACHINE=qemux86-64, qemuarm, qemuarm64, raspberrypi4-64
 - kirkstone, clang,  MACHINE=qemux86-64, qemuarm, qemuarm64, raspberrypi4-64
 - dunfell, clang**,  MACHINE=qemux86-64, qemuarm, qemuarm64, raspberrypi4-64***

** Please note that Chromium requires below set-up when on dunfell
branch.
 - The clang version to be >= 14 and for that, use the latest
   meta-clang/dunfell-clang14 branch.
 - Require the latest meta-oe with Nodejs 14.x support.
 - Add the PREFERRED_VERSION_nodejs-native = "14.%" in conf/local.conf
   file.

*** Please note that there currently is a problem on RPi4/dunfell where
Chromium crashes because of an illegal instruction error.

Signed-off-by: Max Ihlenfeldt <max@igalia.com>

### CODE REVIEW

**Comment by MaxIhlenfeldt** [comment]
Will update the PR description and commit message with the detailed changelog later today. @nrpt-m not sure if you're around this week, if so, testing would be greatly appreciated!

**Comment by nrpt-m** [comment]
> Will update the PR description and commit message with the detailed changelog later today. @nrpt-m not sure if you're around this week, if so, testing would be greatly appreciated!

Sure, will start the testing from today.

**Comment by MaxIhlenfeldt** [comment]
As always, feel free to update and merge this PR without me while I'm OOO :slightly_smiling_face:

**Comment by TheNathan0** [comment]
Great work as usual!  Didn't some V4L2 decoder stuff get upsrteamed as well?  Shouldn't this mean building Chromium with V4L2 decoding options enabled won't result in a build failure?

**Comment by nrpt-m** [comment]
@MaxIhlenfeldt, @rakuco & @kraj 
Have completed the builds & testing in master, kirkstone, dunfell & mickledore branches for all these below systems and chromium worked well in all these systems except rpi4. Have given the rpi4 images of all these above branches to @rwmacleod. Once, he finishes the testing on rpi4 than I will update the results here.

- chromium-ozone-wayland: qemux86-64

- chromium-x11: qemux86-64, qemuarm, qemuarm64, raspberrypi4-64**

cc: @rwmacleod

**Comment by kraj** [comment]
> @MaxIhlenfeldt, @rakuco & @kraj Have completed the builds & testing in master, kirkstone, dunfell & mickledore branches for all these below systems and chromium worked well in all these systems except rpi4.
> 
> * chromium-ozone-wayland: qemux86-64
> * chromium-x11: qemux86-64, qemuarm, qemuarm64, raspberrypi4-64**
> 
> raspberrypi4-64**: Have given the rpi4 images of all these above branches to @rwmacleod. Once, he finishes the testing on rpi4 than I will update the results here. cc: @rwmacleod

thanks @nrpt-m I guess it would be good to add `nanbield` as well, perhaps replace `mickledore` with it
I will try to do a musl build and boot cycle in few days.

**Comment by nrpt-m** [comment]
> raspberrypi4-64**: Have given the rpi4 images of all these above branches to @rwmacleod. Once, he finishes the testing on rpi4 than I will update the results here. cc: @rwmacleod

Please find the below test results of rpi4 image with different branches.

- rpi4/master: Chromium works well with 526/555 html5test.com test score.
- rpi4/kirkstone: There multiple boot failure attempts finally booted and Chromium worked well with 526/555 html5test.com test score.
- rpi4/dunfell: Chromium launch fails with **illegal instruction error**.
- rpi4/mickledore: Chromium works well with 526/555 html5test.com test score.

**Comment by nrpt-m** [comment]
> thanks @nrpt-m I guess it would be good to add `nanbield` as well, perhaps replace `mickledore` with it I will try to do a musl build and boot cycle in few days.

Sure @kraj , will also test with nanbield branch as well.

**Comment by nrpt-m** [comment]
> Sure @kraj , will also test with nanbield branch as well.

@kraj , Have completed the builds & testing in nanbield branch for all these below systems and chromium worked well in all these systems.

- chromium-ozone-wayland: qemux86-64

- chromium-x11: qemux86-64, qemuarm, qemuarm64, raspberrypi4-64

**Review by rakuco — APPROVED** [review]
lgtm from my side

**Comment by MaxIhlenfeldt** [comment]
Thanks for reviewing and testing! I've updated the commit message and PR description with the test results.

**Pull request merged**
