### PR TITLE
chromium: update to 101.0.4951.41

### LINKED ISSUE #632: chromium: update to 101.0.4951.41
https://chromereleases.googleblog.com/2022/04/stable-channel-update-for-desktop_26.html

### PR DESCRIPTION
**Pull request by msisov**
Release notes:
https://chromereleases.googleblog.com/2022/04/stable-channel-update-for-desktop_26.html

License changes:
---------------

Removed licenses:
  * chromeos/third_party/android_bionic_libc/NOTICE
  - Remove unused chromeos/third_party
  - https://chromium-review.googlesource.com/c/chromium/src/+/3487892

Updated licesnes:
  * third_party/libjpeg_turbo/LICENSE.md
  - Roll src/third_party/libjpeg_turbo/ 02959c3ee..22f1a22c9 (1 commit)
  - https://chromium-review.googlesource.com/c/chromium/src/+/3500594

---------------

Test-built

* chromium-ozone-wayland:

    honister, clang, MACHINE="intel-corei7-64"
    hardknott, clang, MACHINE="raspberrypi3"
    dunfell, clang**, MACHINE="qemuarm64"

* chromium-x11

    honister, clang, MACHINE="raspberrypi3"
    hardknott, clang, MACHINE="raspberrypi3"
    dunfell, clang**, MACHINE="raspberrypi3"

** Please note that Chromium requires clang version to be >= 12.
For that, when on dunfell branch, use meta-clang/clang12 branch.

Fixes #632

### CODE REVIEW

**Review by rakuco — APPROVED** [review]
lgtm

@rwmacleod @r1mikey would you like to give it a spin before we merge the PR?

**Comment by rwmacleod** [comment]
I finally made time to get this set-up. I'll report on the builds for master tomorrow (May 3rd).

**Comment by rwmacleod** [comment]
> I finally made time to get this set-up. I'll report on the builds for master tomorrow (May 3rd).

No issues in building using master for [glibc|musl]: qemux86-64, qemuarm64. qx64 runs fine.

**Comment by rakuco** [comment]
Thanks for testing. @msisov feel free to merge this PR, thanks for working on it!

**Pull request merged**
