### PR TITLE
chromium: update to 106.0.5249.119

### LINKED ISSUE #669: chromium: Update to 106.0.5249.119
https://chromereleases.googleblog.com/2022/10/stable-channel-update-for-desktop_11.html

I won't get to this for a few weeks so if anyone else is interested, please let us all know.

### PR DESCRIPTION
**Pull request by msisov**
```
Release notes -
https://chromereleases.googleblog.com/2022/10/stable-channel-update-for-desktop_11.html

License changes:
----------------

Added licenses:
  * third_party/bidimapper/LICENSE
  - https://chromium-review.googlesource.com/c/chromium/src/+/3769895

Removed licenses: (none)

Updated licenses: (none)

Test-built:
-----------

* chromium-ozone-wayland:
 - master, clang,    MACHINE=qemuarm64
 - kirkstone, clang, MACHINE=raspberrypi3

* chromium-x11
 - master, clang**, MACHINE=qemux86-64, qemuarm64
 - kirkstone, clang**, MACHINE=qemux86-64, qemuarm64, qemuarm
 - dunfell, clang**, MACHINE=raspberrypi3

** Please note that Chromium requires clang version to be >= 12. For that, when on dunfell branch, use the meta-clang/clang12 branch.

Signed-off-by: Maksim Sisov <msisov@igalia.com>
```

Fixes #669

### CODE REVIEW

**Comment by msisov** [comment]
@rwmacleod fyi

**Review by rakuco — APPROVED** [review]
Looks fine to me, I'd just wait for @rwmacleod's sign-off and possible extra testing before merging.

One nit about the commit message: there have been more stable channel updates between 105.0.5195.102 and 106.0.5249.119, so it would be good to include links to them as well:
* https://chromereleases.googleblog.com/2022/09/stable-channel-update-for-desktop_14.html
* https://chromereleases.googleblog.com/2022/09/stable-channel-update-for-desktop_27.html
* https://chromereleases.googleblog.com/2022/09/stable-channel-update-for-desktop_30.html
* https://chromereleases.googleblog.com/2022/10/stable-channel-update-for-desktop.html

**Comment by kraj** [comment]
Did you also rebase musl patches ?

**Comment by msisov** [comment]
> Did you also rebase musl patches ?

No, I didn't. Do you want me to do that or can you help with this?

**Review by rwmacleod — COMMENTED** [review]
Diffs look fine. building chromium-x11 for master now. 
I will try to look at the musl patches but that won't happen today.

**Comment by rwmacleod** [comment]
Works find on master but I'll make note of the 'usual' warnings/errors here in case anyone thinks they should be investigated or fixed:
ERROR:bus.cc(399)] Failed to connect to the bus: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeo.
ERROR:bus.cc(399)] Failed to connect to the bus: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeo.
ERROR:egl_util.cc(44)] Failed to load GLES library: libGLESv2.so.2: libGLESv2.so.2: cannot open shared object file: No such file or directory
ERROR:bus.cc(399)] Failed to connect to the bus: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeo.
ERROR:bus.cc(399)] Failed to connect to the bus: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeo.
ERROR:viz_main_impl.cc(186)] Exiting GPU process due to errors during initialization
ERROR:bus.cc(399)] Failed to connect to the bus: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeo.
ERROR:bus.cc(399)] Failed to connect to the bus: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeo.
ERROR:egl_util.cc(44)] Failed to load GLES library: libGLESv2.so.2: libGLESv2.so.2: cannot open shared object file: No such file or directory
ERROR:viz_main_impl.cc(186)] Exiting GPU process due to errors during initialization
ERROR:angle_platform_impl.cc(43)] Display.cpp:997 (initialize): ANGLE Display::initialize error 0: Internal Vulkan error (-3): Initialization of an object could not be completed for implementation-specific reas.
 ANGLE Display::initialize error 0: Internal Vulkan error (-3): Initialization of an object could not be completed for implementation-specific reasons, in ../../third_party/angle/src/libANGLE/renderer/vulkan/Re.
ERROR:gl_display.cc(508)] EGL Driver message (Critical) eglInitialize: Internal Vulkan error (-3): Initialization of an object could not be completed for implementation-specific reasons, in ../../third_party/an.
ERROR:gl_display.cc(920)] eglInitialize SwANGLE failed with error EGL_NOT_INITIALIZED
ERROR:gl_ozone_egl.cc(23)] GLDisplayEGL::Initialize failed.
ERROR:viz_main_impl.cc(186)] Exiting GPU process due to errors during initialization
ERROR:gpu_init.cc(521)] Passthrough is not supported, GL is disabled, ANGLE is

The 'bus' ones, we might want to add an optional dependency to address but they seem to be mostly harmless.
The graphics tests->errors I have assumed are 'normal'.

Next stop, qemuarm64 on master then kirkstone.

**Comment by msisov** [comment]
> Works find on master but I'll make note of the 'usual' warnings/errors here in case anyone thinks they should be investigated or fixed: ERROR:bus.cc(399)] Failed to connect to the bus: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeo. ERROR:bus.cc(399)] Failed to connect to the bus: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeo. ERROR:egl_util.cc(44)] Failed to load GLES library: libGLESv2.so.2: libGLESv2.so.2: cannot open shared object file: No such file or directory ERROR:bus.cc(399)] Failed to connect to the bus: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeo. ERROR:bus.cc(399)] Failed to connect to the bus: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeo. ERROR:viz_main_impl.cc(186)] Exiting GPU process due to errors during initialization ERROR:bus.cc(399)] Failed to connect to the bus: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeo. ERROR:bus.cc(399)] Failed to connect to the bus: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeo. ERROR:egl_util.cc(44)] Failed to load GLES library: libGLESv2.so.2: libGLESv2.so.2: cannot open shared object file: No such file or directory ERROR:viz_main_impl.cc(186)] Exiting GPU process due to errors during initialization ERROR:angle_platform_impl.cc(43)] Display.cpp:997 (initialize): ANGLE Display::initialize error 0: Internal Vulkan error (-3): Initialization of an object could not be completed for implementation-specific reas. ANGLE Display::initialize error 0: Internal Vulkan error (-3): Initialization of an object could not be completed for implementation-specific reasons, in ../../third_party/angle/src/libANGLE/renderer/vulkan/Re. ERROR:gl_display.cc(508)] EGL Driver message (Critical) eglInitialize: Internal Vulkan error (-3): Initialization of an object could not be completed for implementation-specific reasons, in ../../third_party/an. ERROR:gl_display.cc(920)] eglInitialize SwANGLE failed with error EGL_NOT_INITIALIZED ERROR:gl_ozone_egl.cc(23)] GLDisplayEGL::Initialize failed. ERROR:viz_main_impl.cc(186)] Exiting GPU process due to errors during initialization ERROR:gpu_init.cc(521)] Passthrough is not supported, GL is disabled, ANGLE is
> 
> The 'bus' ones, we might want to add an optional dependency to address but they seem to be mostly harmless. The graphics tests->errors I have assumed are 'normal'.
> 
> Next stop, qemuarm64 on master then kirkstone.

Is that x11? Are you running with gpu available or not?

**Comment by Oquirella** [comment]
@rwmacleod i get the same erros with chromium-x11, but somehow chromium works fine? chrome://gpu tells me that hardware acceleration is disabled...

**Comment by msisov** [comment]
Are we not copying libGLESv2 into the image?

**Comment by rakuco** [comment]
We are: https://github.com/OSSystems/meta-browser/blob/0f11e5ed0da3a622bbd7952400e7470815ded96a/meta-chromium/recipes-browser/chromium/chromium-gn.inc#L475

**Comment by Oquirella** [comment]
@rakuco  Chromium is searching for "libGLESv2.so.2" not for "libGLESv2.so".

**Comment by rakuco** [comment]
Ah yes, Chromium ships libGLESv2.so (even in the official packages), libGLESv2.so.2 is expected to come from the system as far as I can see, and the ANGLE libraries (which we install) are used depending on the GL backend being used. @msisov knows more about this area though.

**Comment by rwmacleod** [comment]
> Is that x11? Are you running with gpu available or not?

Yes, chromium-x11. This is poky for qemux86-64 and runqemu kvm publicvnc which I will not be gpu accelerated.

**Review by rwmacleod — APPROVED** [review]

**Comment by rwmacleod** [comment]
I've build and tested qemux86-64, qemuarm64 for kirkstone as well. LGTM!

**Comment by msisov** [comment]
> @rakuco Chromium is searching for "libGLESv2.so.2" not for "libGLESv2.so". We are not installing libGLESv2.so.2.

indeed [1]. And it has been like that since 2018. Do yocto systems name that somehow differently? On my Linux machine, I see the following - 

```
$ cd /lib
$ find -iname "libGLESv2*"
./x86_64-linux-gnu/libGLESv2.so.2
./x86_64-linux-gnu/libGLESv2.so
./x86_64-linux-gnu/libGLESv2.so.2.1.0
```

If you (I mean @Oquirella), create a symlink for libGLESv2.so and name it as libGLESv2.so.2, will chromium-x11 start hw accelerated?

[1] https://source.chromium.org/chromium/chromium/src/+/main:ui/ozone/common/egl_util.cc;l=30?q=libGLESv2.so.2&ss=chromium%2Fchromium%2Fsrc

**Comment by msisov** [comment]
> I've build and tested qemux86-64, qemuarm64 for kirkstone as well. LGTM!

qemux86-64 on master and qemux86-64, qemuarm64 on kirkstone. Is that correct? I just wanted to clarify this and add that to the commit message.

**Comment by rwmacleod** [comment]
> > I've build and tested qemux86-64, qemuarm64 for kirkstone as well. LGTM!
> 
> qemux86-64 on master and qemux86-64, qemuarm64 on kirkstone. Is that correct? I just wanted to clarify this and add that to the commit message.
* chromium-x11
 - master, clang**, MACHINE=qemux86-64, qemuarm64
 - kirkstone, clang**, MACHINE=qemux86-64, qemuarm64, qemuarm

**Comment by rakuco** [comment]
Are we ready to go now? Just checking because this update has had an unusual amount of comments :-)

**Comment by rakuco** [comment]
Thank you both. @msisov, over to you :-)

**Comment by msisov** [comment]
Sorry for the delay. And thanks to everyone involved.

**Pull request merged**
