### PR TITLE
chromium: Update to 72.0.3626.96

### PR DESCRIPTION
**Pull request by rakuco**
Release announcement:
https://chromereleases.googleblog.com/2019/02/stable-channel-update-for-desktop.html

chromium-x11 was test-built on:
* rocko, GCC 7 and MACHINE="qemuarm64"
* sumo, GCC 7, MACHINE="raspberrypi3" and TOOLCHAIN_pn-chromium-x11="clang"
* thud, GCC 8, MACHINE="intel-core-i7-64" and MACHINE="intel-core2-32"

chromium-ozone-wayland was test-built on:
* thud, GCC 8, MACHINE="qemuarm64"

### CODE REVIEW

**Comment by rakuco** [comment]
@otavio @msisov

**Comment by kraj** [comment]
@rakuco can you try meta-clang/master as well if you add master to your test matrix?

**Comment by rakuco** [comment]
> @rakuco can you try meta-clang/master as well if you add master to your test matrix?

I can try, I just don't have plans to test master right now (except on special occasions like #219) because of the amount of builds I already have to launch.

**Comment by rakuco** [comment]
I'll close this one because a new stable version's been released.

**Pull request closed without merging**
