### PR TITLE
chromium: update to 116.0.5845.179

### PR DESCRIPTION
**Pull request by MaxIhlenfeldt**
chromium: update to 116.0.5845.179

Release notes:
    https://chromereleases.googleblog.com/2023/08/stable-channel-update-for-desktop_15.html
    https://chromereleases.googleblog.com/2023/08/chrome-desktop-stable-update.html
    https://chromereleases.googleblog.com/2023/08/stable-channel-update-for-desktop_29.html
    https://chromereleases.googleblog.com/2023/09/stable-channel-update-for-desktop.html

Build and patch changes:
------------------------

Drop 0023-Backport-IWYU-for-translate-TranslateUILanguagesMana.patch and
0029-Backport-IWYU-for-translate-TranslateUiLanguagesMana.patch as they
are included upstream now.

Update `0020-Revert-__attribute__-and-alignas-changes.patch` to omit the
[[clang::noinline]] and [[clang::always_inline]] attributes. They aren't
recognized by clang 14 and generate lots of warnings cluttering the
logs.

Add some more build error fixes to 0021-Add-missing-typename-s.patch.

Remove one build error fix from
0034-Avoid-parenthesized-initialization-of-aggregates.patch that isn't
needed any more due to upstream changes, and add a few new ones.

Add 0036-Avoid-std-ranges-find_if.patch to fix build errors with
clang < 16.

Add 0037-Fix-constexpr-variable-cannot-have-non-literal-type-.patch to
fix build errors with clang < 16.

Add 0038-Fix-undefined-symbol-PaintOpWriter-SerializedSize-un.patch to
fix a build/linker error with clang 14.

Rebase remaining patches.

License changes:
----------------

Added licenses:
  * base/allocator/partition_allocator/third_party/apple_apsl/LICENSE
  - https://chromium-review.googlesource.com/c/chromium/src/+/4568045

  * third_party/android_toolchain/NOTICE
  - https://chromium-review.googlesource.com/c/chromium/src/+/4559153,
    https://chromium-review.googlesource.com/c/chromium/src/+/4609181

  * third_party/anonymous_tokens/src/LICENSE
  - https://chromium-review.googlesource.com/c/chromium/src/+/4545718

  * third_party/cpu_features/src/LICENSE
  - https://chromium-review.googlesource.com/c/chromium/src/+/4545271

  * third_party/libavifinfo/LICENSE
  - https://chromium-review.googlesource.com/c/chromium/src/+/4593550

Removed licenses: none.

Updated licenses:
  * third_party/icu/LICENSE
  - https://chromium-review.googlesource.com/c/chromium/deps/icu/+/4615291

  * third_party/vulkan-deps/vulkan-validation-layers/src/LICENSE.txt
  - https://github.com/KhronosGroup/Vulkan-ValidationLayers/commit/1f33cbd222907eb6e6795a55c9859975609f66ba

Test-built (big thanks to @nrpt-m):
-----------------------------------

* chromium-ozone-wayland:
  - master, clang,     MACHINE=qemux86-64
  - mickledore, clang, MACHINE=qemuarm64, qemux86-64
  - kirkstone, clang,  MACHINE=qemux86-64, raspberrypi4-64
  - dunfell, clang**,  MACHINE=qemux86-64

* chromium-x11
  - master, clang,     MACHINE=qemux86-64, qemuarm, qemuarm64, raspberrypi4-64
  - mickledore, clang, MACHINE=qemux86-64, qemuarm, qemuarm64, raspberrypi4-64
  - kirkstone, clang,  MACHINE=qemux86-64, qemuarm, qemuarm64, raspberrypi4-64
  - dunfell, clang**,  MACHINE=qemux86-64, qemuarm, qemuarm64, raspberrypi4-64

** Please note that Chromium requires below set-up when on dunfell
branch.
 - The clang version to be >= 14 and for that, use the latest
   meta-clang/dunfell-clang14 branch.
 - Require the latest meta-oe with Nodejs 14.x support.
 - Add the PREFERRED_VERSION_nodejs-native = "14.%" in conf/local.conf
   file.

### CODE REVIEW

**Comment by MaxIhlenfeldt** [comment]
@rakuco as this builds upon #741, I had to include that in this PR. The actual changes introduced by this PR are in [this commit](https://github.com/OSSystems/meta-browser/pull/750/commits/b09258f2ca4a25bf8bd6b3947f3e2befb38aac81).

@nrpt-m as always, testing would be greatly appreciated!

**Comment by nrpt-m** [comment]
@MaxIhlenfeldt @rakuco 
Have completed the builds & testing in master branch for all these below systems and chromium worked well in all these systems.
- chromium-ozone-wayland: qemux86-64

- chromium-x11: qemux86-64, qemuarm, qemuarm64, raspberrypi4-64**

** @rwmacleod is away this week so, have just built rpi4 image but didn't test it. I don't have rpi4 setup so, checking with my colleagues for testing rpi4 image and once done will update here.

Next, starting with kirkstone, dunfell & mickledore branches.

**Comment by nrpt-m** [comment]
@MaxIhlenfeldt @rakuco
Have completed the builds & testing in kirkstone and dunfell branches for all these below systems and chromium worked well in all these systems.

- chromium-ozone-wayland: qemux86-64

- chromium-x11: qemux86-64, qemuarm, qemuarm64, raspberrypi4-64**

** Successfully built the rpi4 images but haven't tested yet on RPI4.

Next, starting with mickledore branch.

**Comment by nrpt-m** [comment]
@MaxIhlenfeldt @rakuco
Have completed the builds & testing in mickledore branch as well for all these below systems and chromium worked well in all these systems.

chromium-ozone-wayland: qemux86-64

chromium-x11: qemux86-64, qemuarm, qemuarm64, raspberrypi4-64**

** Successfully built the rpi4 image but haven't tested yet on RPI4.

**Review by rakuco — APPROVED** [review]
lgtm

**Comment by rakuco** [comment]
Thanks @nrpt-m!

I've rebased this PR on top of master and adjusted the commit and PR messages to include your test results. Time to merge!

**Pull request merged**
