### PR TITLE
chromium-x11: Import patch to fix the build with GCC 8

### LINKED ISSUE #129: chromium-x11 do_compile: ninja: build stopped: subcommand failed.
Hi,
using the latest master (1cd38d701a49eade80a04140f70d3383117b9745) fails the build of chromium-x11_67.0.3396.87 for armhf (i.MX6).

Following error occurs repeatedly (please find more details in the attached log):
```
error: cannot convert 'const mojo::ScopedInterfaceEndpointHandle' to 'bool' in return
```

I'm using following branches and configuration:
```
Build Configuration:
BB_VERSION           = "1.39.0"
BUILD_SYS            = "x86_64-linux"
NATIVELSBSTRING      = "universal"
TARGET_SYS           = "arm-myos-linux-gnueabi"
MACHINE              = "sdimx6"
DISTRO               = "myos"
DISTRO_VERSION       = "0.0.1"
TUNE_FEATURES        = "arm armv7a vfp thumb neon callconvention-hard"
TARGET_FPU           = "hard"
meta
meta-poky
meta-yocto-bsp       = "master:c7c64baa411fd96886918c235b851ae3e5a6a61f"
meta-oe
meta-multimedia      = "master:4517d1c695efd0b175f4e7242e1a7bb4361527d9"
meta-java            = "master-next:c8f7e412aaee4e41ec8ff980f463536c757538d0"
meta-freescale       = "master:aa3c33cdcd9c336ec39765d5a73dc62f87393f2c"
meta-browser         = "master:1cd38d701a49eade80a04140f70d3383117b9745"
```

The complete do_compile log is here: [log.do_compile.log](https://github.com/OSSystems/meta-browser/files/2148580/log.do_compile.log)

Any help is much appreciated!

regards;Richard.L

### PR DESCRIPTION
**Pull request by rakuco**
Fixes #129.

### CODE REVIEW

**Comment by rakuco** [comment]
@otavio @g0hl1n some additional testing would be appreciated

I've only managed to test that my existing build with Yocto sumo (GCC 7) doesn't break with this, although I've been using this same patch with my Clear Linux (GCC 8) build for several weeks now.

**Comment by g0hl1n** [comment]
My first test build failed with the following error message (RAM & disk are not an issue as they are always below 50%):
```
| In file included from /build/master/tmp/work/armv7at2hf-neon-imx-myos-linux-gnueabi/chromium-x11/67.0.3396.87-r0/recipe-sysroot/usr/include/c++/8.1.0/memory:80,
|                  from ../../third_party/blink/renderer/core/style/data_equivalency.h:8,
|                  from ../../third_party/blink/renderer/core/css/css_value.h:26,
|                  from gen/third_party/blink/renderer/core/css/properties/css_property.h:17,
|                  from ../../third_party/blink/renderer/core/css/properties/shorthand.h:8,
|                  from gen/third_party/blink/renderer/core/css/properties/shorthands/grid_template.h:16,
|                  from ../../third_party/blink/renderer/core/css/properties/shorthands/grid_template_custom.cc:5:
| /build/master/tmp/work/armv7at2hf-neon-imx-myos-linux-gnueabi/chromium-x11/67.0.3396.87-r0/recipe-sysroot/usr/include/c++/8.1.0/bits/unique_ptr.h: In instantiation of 'std::__uniq_ptr_impl<_Tp, _Dp>::pointer& std::__uniq_ptr_impl<_Tp, _Dp>::_M_ptr() [with _Tp = netwo
rk::mojom::blink::HttpRequestHeaders; _Dp = std::default_delete<network::mojom::blink::HttpRequestHeaders>; std::__uniq_ptr_impl<_Tp, _Dp>::pointer = network::mojom::blink::HttpRequestHeaders*]':
| /build/master/tmp/work/armv7at2hf-neon-imx-myos-linux-gnueabi/chromium-x11/67.0.3396.87-r0/recipe-sysroot/usr/include/c++/8.1.0/bits/unique_ptr.h:380:6:   required from 'void std::unique_ptr<_Tp, _Dp>::reset(std::unique_ptr<_Tp, _Dp>::pointer) [with _Tp = network::mo
jom::blink::HttpRequestHeaders; _Dp = std::default_delete<network::mojom::blink::HttpRequestHeaders>; std::unique_ptr<_Tp, _Dp>::pointer = network::mojom::blink::HttpRequestHeaders*]'
| ../../mojo/public/cpp/bindings/struct_ptr.h:62:18:   required from 'void mojo::StructPtr<S>::reset() [with S = network::mojom::blink::HttpRequestHeaders]'
| gen/services/network/public/mojom/http_request_headers.mojom-blink.h:349:97:   required from here
| /build/master/tmp/work/armv7at2hf-neon-imx-myos-linux-gnueabi/chromium-x11/67.0.3396.87-r0/recipe-sysroot/usr/include/c++/8.1.0/bits/unique_ptr.h:149:55: internal compiler error: Segmentation fault
|        pointer&   _M_ptr() { return std::get<0>(_M_t); }
|                                                        ^
| Please submit a full bug report,
| with preprocessed source if appropriate.
| See <https://gcc.gnu.org/bugs/> for instructions.

```

I used current masters:
```
poky = "master:7cb125d7ee4b80fb33d87bdd0b257bc6daaff051"
meta-openembedded = "master:4517d1c695efd0b175f4e7242e1a7bb4361527d9"
meta-freescale       = "master:aa3c33cdcd9c336ec39765d5a73dc62f87393f2c"
meta-browser         = "master:8e159ff95e0583c4a821d5e59c8bb1972820f10d"
```

Any suggestions? Hints?

**Comment by rakuco** [comment]
Hmm, that one looks very odd. Apparently GCC is misbehaving and crashing when trying to build some bit of Chromium code; in this case it's either GCC or the maintainers of the GCC recipe that need to be poked for a fix.

**Comment by otavio** [comment]
Which machine target are you using for the build?

**Comment by g0hl1n** [comment]
I'm building for an i.MX6 machine from meta-freescale (basically the same as imx6qdlsabreauto except the kernel & dt).
Does it work for you using another machine?

**Comment by otavio** [comment]
We can test this but please open an issue and provide this information there so we track this individually.

**Comment by g0hl1n** [comment]
Ok. Thank you for you help.
Nonetheless it seems it's working with current master branches of poky and meta-openembedded. :+1:

**Comment by schnitzeltony** [comment]
FWIW: For my environment (Raspi3 / gcc8) I can confirm that this patch fixes build.

Before: do_compile failed
After: Clean build

Thanks

**Pull request merged**
