### PR TITLE
chromium: Update to 72.0.3626.119

### PR DESCRIPTION
**Pull request by rakuco**
Release announcement:
https://chromereleases.googleblog.com/2019/02/stable-channel-update-for-desktop_21.html

chromium-x11 was test-built on:
* rocko, GCC 7 and MACHINE="qemuarm64"
* sumo, GCC 7, MACHINE="raspberrypi3" and TOOLCHAIN_pn-chromium-x11="clang"
* thud, GCC 8, MACHINE="intel-core-i7-64" and MACHINE="intel-core2-32"

chromium-ozone-wayland was test-built on:
* thud, GCC 8, MACHINE="qemuarm64"

### CODE REVIEW

**Comment by msisov** [comment]
Thanks. I was planning to do it as well. Well, I will just merge more backported patches then.

**Comment by rakuco** [comment]
> Well, I will just merge more backported patches then.

Do you mean cr-oz-wl needs additional patches in .119 compared to .109?

**Comment by msisov** [comment]
The Ozone/Wayland project is a work in progress. We implement more features, fix more bugs. Since the last time update, we have additional dozen of patches landed, which worth backporting to improve the user experience.

**Comment by rakuco** [comment]
OK, so from what I understood it's unrelated to this specific update.

**Comment by msisov** [comment]
correct.

**Comment by rakuco** [comment]
Right, sorry for the confusion :)

**Comment by msisov** [comment]
@otavio @kraj do you have any questions?

**Pull request merged**
