### PR TITLE
chromium: Fix build on 32bit arches with 64bit time_t

### PR DESCRIPTION
**Pull request by kraj**
64bit time_t is being added to glibc/musl and will be enabled by default
for 32bit arches atleast its is on musl. This patch ensures that we use
portable defines in a backward compatible way

Signed-off-by: Khem Raj <raj.khem@gmail.com>

### CODE REVIEW

**Comment by kraj** [comment]
Submitted to chromium gerrit as well

https://chromium-review.googlesource.com/c/chromium/src/+/1972680

**Comment by rakuco** [comment]
> Submitted to chromium gerrit as well

Thanks. I've submitted feedback in the bug report and asked for review in Gerrit (your CL was still in the "WIP" state so no emails had been sent yet).

**Comment by rakuco** [comment]
Given https://chromium-review.googlesource.com/c/chromium/src/+/1972680 was merged upstream, can you backport that commit (following our naming conventions etc, minus the change to `AUTHORS` if it doesn't merge cleanly)?

I also see that you pushed some clang10 fixes to this PR in a separate commit. I suggest creating a separate PR for those changes since they introduce quite a few new patches, some of which have no indication of whether they were sent upstream.

**Comment by kraj** [comment]
I would close this pull since it’s upstream one of these regular updates will bring it in anyway and I have it in my fork for my needed

**Comment by rakuco** [comment]
OK, feel free to then :-)

**Pull request closed without merging**
