### PR TITLE
chromium: Update to 131.0.6778.85

### PR DESCRIPTION
**Pull request by MaxIhlenfeldt**
Fixes OSSystems#848.

Release notes:
    https://chromereleases.googleblog.com/2024/11/stable-channel-update-for-desktop_12.html
    https://chromereleases.googleblog.com/2024/11/stable-channel-update-for-desktop_19.html

Build and patch changes:
------------------------

Rebase patches.

License changes:
----------------

Added licenses:
  * third_party/android_deps/libs/org_jspecify_jspecify/LICENSE
  - https://chromium-review.googlesource.com/c/chromium/src/+/5898977

  * third_party/devtools-frontend/src/front_end/third_party/json5/LICENSE
  - https://chromium-review.googlesource.com/c/devtools/devtools-frontend/+/5920841

  * third_party/ink/LICENSE
  - https://chromium-review.googlesource.com/c/chromium/src/+/5530802

  * third_party/ink_stroke_modeler/LICENSE
  - https://chromium-review.googlesource.com/c/chromium/src/+/5530867

Removed licenses:
  * third_party/catapult/third_party/httplib2/LICENSE
  - https://chromium-review.googlesource.com/c/catapult/+/5858365

Updated licenses: None.

Test-built (big thanks to @SoumyaWind):
---------------------------------------

* chromium-ozone-wayland:
 - master, clang,    MACHINE=qemux86-64
 - styhead, clang,   MACHINE=raspberrypi4-64
 - scarthgap, clang, MACHINE=qemux86-64

* chromium-x11:
 - master, clang,    MACHINE=qemuarm, qemuarm64, qemux86-64, raspberrypi4-64
 - scarthgap, clang, MACHINE=qemuarm, qemuarm64, qemux86-64, raspberrypi4-64

### CODE REVIEW

**Comment by MaxIhlenfeldt** [comment]
Uploading as a draft because the build will currently fail on Scarthgap, because upstream now requires Rust 1.78 and Scarthgap only has 1.75. However, I reached out to the maintainer of meta-lts-mixins' `kirkstone/rust` branch (which currently has Rust 1.78), and he told me:

> It has been my plan to create a scarthgap/rust when required, and I
mentioned on the YP call this week that my goal is to produce the initial
version for next week.  Someone else just posted their initial take on one
as well, though their usecase is different, and I suspect we'll end up with
myself as maintainer.

I don't think it makes sense to create a patch to temporarily get upstream's Rust requirement back down to 1.75 when we can just wait until next week and then require meta-lts-mixins' new `scarthgap/rust` branch.

wdyt?

**Comment by MaxIhlenfeldt** [comment]
@SoumyaWind as always, testing would be greatly appreciated! Note that the Scarthgap build currently doesn't work as mentioned in my previous comment. I also added a Styhead build to my own testing setup, not sure if you want to do the same.

**Comment by SoumyaWind** [comment]
@MaxIhlenfeldt ok, I will start testing.

**Comment by SoumyaWind** [comment]
@MaxIhlenfeldt, I have completed the testing for below configuration for Poky master with latest changes. Here are the results for your reference:

1. **chromium-x11 on qemux86-64 target**: Compiled successfully without any build issues. Verified chromium version using qemux86-64 emulator
2. **chromium-x11 on qemuarm target**: Without debug configuration, encountered the following error during build -
>| arm-poky-linux-gnueabi-ld.lld: error: output file too large: 7007646508 bytes
>| section sizes:
>| .interp 25
>| .note.ABI-tag 32
>| .note.crashpad.info 28
>| .note.gnu.build-id 36
>| .dynsym 24992
>| .gnu.version 3124
>| .gnu.version_r 1040
>| .gnu.hash 372
>| .dynstr 35202
>| .rel.dyn 7067368
>| .ARM.exidx 9392
>| .rel.plt 11504
>| .rodata 14590477
>| .ARM.extab 13016
>| .eh_frame_hdr 12
>| .eh_frame 4
>| .text 145184760
>| .init 28
>| .fini 8
>| malloc_hook 500
>| .plt 23040
>| .tdata 168
>| .tbss 2988
>| .fini_array 4
>| .init_array 8
>| .data.rel.ro 4853928
>| .dynamic 472
>| .got 54448
>| .got.plt 5764
>| .relro_padding 76
>| .data 380712
>| .tm_clone_table 0
>| protected_memory 4118
>| protected_memory_buffer 1
>| .bss 1592036
>| .comment 133
>| .ARM.attributes 59
>| .debug_aranges 264
>| .debug_info 3728717391
>| .debug_abbrev 143101899
>| .debug_line 280590992
>| .debug_str 1402165233
>| .debug_line_str 4109490
>| .debug_rnglists 154966972
>| .debug_loclists 331479399
>| .debug_str_offsets 600327336
>| .debug_addr 38089608
>| .debug_frame 22729536
>| .symtab 31703408
>| .shstrtab 586
>| .strtab 97392545
>|
>| arm-poky-linux-gnueabi-clang++: error: linker command failed with exit code 1 (use -v to see invocation)
>| ninja: build stopped: subcommand failed.

With GN configuration - is_debug=true, is_official_build=false, symbol_level=2 and with the dependencies:

DISTRO_FEATURES with usrmerge and systemd
VIRTUAL-RUNTIME_init_manager to systemd
systemd and systemd-dev in IMAGE_INSTALL
The build was successful for qemuarm, and I was able to verify chromium version using qemuarm emulator
3. **chromium-x11 on qemuarm64 target**: Compiled successfully without build issues. Verified chromium version using qemuarm64 emulator
4. **chromium-x11 on raspberrypi4-64 target**: Compiled successfully without any build issues. I could not test on actual hardware due to unavailability.
5. **chromium-ozone-wayland on qemux86-64 target**: Compiled successfully without any build issues, verified chromium version using qemux86-64 emulator

**Comment by SoumyaWind** [comment]
I also completed testing with the following configurations for poky styhead with the latest changes. Below are the results for your reference:

1. **chromium-x11 on qemux86-64 target**: Compiled successfully without any build issues, verified chromium version using the qemux86-64 emulator.
2. **chromium-x11 on qemuarm target**: Without debug configuration, encountered the following error during build -

>| arm-poky-linux-gnueabi-ld.lld: error: output file too large: 7007662280 bytes
>| section sizes:
>| .interp 25
>| .note.ABI-tag 32
>| .note.crashpad.info 28
>| .note.gnu.build-id 36
>| .dynsym 24992
>| .gnu.version 3124
>| .gnu.version_r 1040
>| .gnu.hash 372
>| .dynstr 35202
>| .rel.dyn 7067856
>| .ARM.exidx 9464
>| .rel.plt 11504
>| .rodata 14594573
>| .ARM.extab 13292
>| .eh_frame_hdr 12
>| .eh_frame 4
>| .text 145179800
>| .init 28
>| .fini 8
>| malloc_hook 500
>| .plt 23040
>| .tdata 168
>| .tbss 2988
>| .fini_array 4
>| .init_array 8
>| .data.rel.ro 4853864
>| .dynamic 472
>| .got 54448
>| .got.plt 5764
>| .relro_padding 140
>| .data 380712
>| .tm_clone_table 0
>| protected_memory 4118
>| protected_memory_buffer 1
>| .bss 1592036
>| .comment 133
>| .ARM.attributes 59
>| .debug_aranges 264
>| .debug_info 3728722132
>| .debug_abbrev 143102561
>| .debug_line 280590844
>| .debug_str 1402165103
>| .debug_line_str 4109490
>| .debug_rnglists 154966913
>| .debug_loclists 331479330
>| .debug_str_offsets 600328560
>| .debug_addr 38089344
>| .debug_frame 22729512
>| .symtab 31704816
>| .shstrtab 586
>| .strtab 97400971
>|
>| arm-poky-linux-gnueabi-clang++: error: linker command failed with exit code 1 (use -v to see invocation)
>| ninja: build stopped: subcommand failed.

With GN configuration - is_debug=true, is_official_build=false, symbol_level=2 and with the dependencies:
DISTRO_FEATURES with usrmerge and systemd
VIRTUAL-RUNTIME_init_manager to systemd
systemd and systemd-dev in IMAGE_INSTALL
The build was successful for qemuarm, and I was able to verify chromium version using qemuarm emulator
3. **chromium-x11 on qemuarm64 target**: Compiled successfully without any build issues, verified chromium version using the qemuarm64 emulator.
4. **chromium-x11 on raspberrypi4-64 target**:  The meta-raspberrypi layer does not have a styhead branch yet.
5. **chromium-ozone-wayland on qemux86-64 target**: Compiled successfully without any build issues, verified chromium version using the qemux86-64 emulator.

**Comment by MastaG** [comment]
> I also completed testing with the following configurations for poky styhead with the latest changes. Below are the results for your reference:
> 
>     1. **chromium-x11 on qemux86-64 target**: Compiled successfully without any build issues, verified chromium version using the qemux86-64 emulator.
> 
>     2. **chromium-x11 on qemuarm target**: Without debug configuration, encountered the following error during build -
> 
> 
> > | arm-poky-linux-gnueabi-ld.lld: error: output file too large: 7007662280 bytes
> > | section sizes:
> > | .interp 25
> > | .note.ABI-tag 32
> > | .note.crashpad.info 28
> > | .note.gnu.build-id 36
> > | .dynsym 24992
> > | .gnu.version 3124
> > | .gnu.version_r 1040
> > | .gnu.hash 372
> > | .dynstr 35202
> > | .rel.dyn 7067856
> > | .ARM.exidx 9464
> > | .rel.plt 11504
> > | .rodata 14594573
> > | .ARM.extab 13292
> > | .eh_frame_hdr 12
> > | .eh_frame 4
> > | .text 145179800
> > | .init 28
> > | .fini 8
> > | malloc_hook 500
> > | .plt 23040
> > | .tdata 168
> > | .tbss 2988
> > | .fini_array 4
> > | .init_array 8
> > | .data.rel.ro 4853864
> > | .dynamic 472
> > | .got 54448
> > | .got.plt 5764
> > | .relro_padding 140
> > | .data 380712
> > | .tm_clone_table 0
> > | protected_memory 4118
> > | protected_memory_buffer 1
> > | .bss 1592036
> > | .comment 133
> > | .ARM.attributes 59
> > | .debug_aranges 264
> > | .debug_info 3728722132
> > | .debug_abbrev 143102561
> > | .debug_line 280590844
> > | .debug_str 1402165103
> > | .debug_line_str 4109490
> > | .debug_rnglists 154966913
> > | .debug_loclists 331479330
> > | .debug_str_offsets 600328560
> > | .debug_addr 38089344
> > | .debug_frame 22729512
> > | .symtab 31704816
> > | .shstrtab 586
> > | .strtab 97400971
> > |
> > | arm-poky-linux-gnueabi-clang++: error: linker command failed with exit code 1 (use -v to see invocation)
> > | ninja: build stopped: subcommand failed.
> 
> With GN configuration - is_debug=true, is_official_build=false, symbol_level=2 and with the dependencies: DISTRO_FEATURES with usrmerge and systemd VIRTUAL-RUNTIME_init_manager to systemd systemd and systemd-dev in IMAGE_INSTALL The build was successful for qemuarm, and I was able to verify chromium version using qemuarm emulator 3. **chromium-x11 on qemuarm64 target**: Compiled successfully without any build issues, verified chromium version using the qemuarm64 emulator. 4. **chromium-x11 on raspberrypi4-64 target**: The meta-raspberrypi layer does not have a styhead branch yet. 5. **chromium-ozone-wayland on qemux86-64 target**: Compiled successfully without any build issues, verified chromium version using the qemux86-64 emulator.

Like I told you in the other post, you can easily do a release build by omitting `-g` as passed by bitbake.
```
CFLAGS:remove:arm = "-g"
CXXFLAGS:remove:arm = "-g"
```

Then you don't have to change `is_debug` or `is_official_build`.
They are set correctly here: https://github.com/OSSystems/meta-browser/blob/68e8cbf51ac46c8c1b3923ee2b20e27ba9d3faa4/meta-chromium/recipes-browser/chromium/chromium-gn.inc#L178

**Comment by SoumyaWind** [comment]
@MastaG Thank you for the suggestion. I updated the configuration to remove the -g flag for ARM, and the release build worked as expected.

**Comment by MaxIhlenfeldt** [comment]
Right, it seems the Rust backport for Scarthgap might take a bit longer. I just checked and it seems the change should be relatively easy to temporarily revert until we can use Rust 1.78 on Scarthgap: https://chromium-review.googlesource.com/c/chromium/src/+/5913992. I'll update this PR shortly.

**Comment by MaxIhlenfeldt** [comment]
@SoumyaWind can you please test on Scarthgap with the latest commit I just pushed? I'm also running some builds on Styhead and master to make sure nothing broke, but I don't think you need to test these two again.

**Comment by SoumyaWind** [comment]
@MaxIhlenfeldt sure, I will start testing on scarthgap branch and update once it is done.

**Comment by SoumyaWind** [comment]
@MaxIhlenfeldt , I have completed testing with the following configurations for poky scarthgap with the latest changes. Here are the results for your reference:

1. **chromium-x11 on qemux86-64 target:** Compiled successfully without any build issues, verified chromium version using the qemux86-64 emulator.
2. **chromium-x11 on qemuarm target:** Compiled successfully without any build issues, verified chromium version using the qemuarm emulator.
3. **chromium-x11 on qemuarm64 target:** Compiled successfully without any build issues, verified chromium version using the qemuarm64 emulator.
4. **chromium-x11 on raspberrypi4-64 target:** Compiled successfully without any build issues. verified chromium version from command line on the Raspberry Pi 4.
5. **chromium-ozone-wayland on qemux86-64 target:** Compiled successfully without any build issues, verified chromium version using the qemux86-64 emulator.

**Comment by MaxIhlenfeldt** [comment]
Thanks, I'd say we're good to go!

**Pull request merged**
