### PR TITLE
chromium: Update to 126.0.6478.126

### LINKED ISSUE #823: Update to Chromium 126
Release notes:
* https://chromereleases.googleblog.com/2024/06/stable-channel-update-for-desktop.html
* https://chromereleases.googleblog.com/2024/06/stable-channel-update-for-desktop_13.html
* https://chromereleases.googleblog.com/2024/06/stable-channel-update-for-desktop_18.html
* https://chromereleases.googleblog.com/2024/06/stable-channel-update-for-desktop_24.html

### PR DESCRIPTION
**Pull request by MaxIhlenfeldt**
Fixes #823.

Release notes:
    https://chromereleases.googleblog.com/2024/06/stable-channel-update-for-desktop.html
    https://chromereleases.googleblog.com/2024/06/stable-channel-update-for-desktop_13.html
    https://chromereleases.googleblog.com/2024/06/stable-channel-update-for-desktop_18.html
    https://chromereleases.googleblog.com/2024/06/stable-channel-update-for-desktop_24.html

Build and patch changes:
------------------------

Drop two backported patches that are included in upstream now.

Rebase remaining patches.

License changes:
----------------

Added licenses:
  * third_party/crabbyavif/LICENSE
  - https://chromium-review.googlesource.com/c/chromium/src/+/5458147

Removed licenses:
  * base/third_party/dynamic_annotations/LICENSE
  - https://chromium-review.googlesource.com/c/chromium/src/+/2544607

  * third_party/android_deps/libs/com_google_android_gms_play_services_places_placereport/LICENSE
  - https://chromium-review.googlesource.com/c/chromium/src/+/5515920

  * third_party/android_deps/libs/com_google_android_gms_play_services_tflite_impl/LICENSE, third_party/android_deps/libs/com_google_android_gms_play_services_tflite_java/LICENSE, third_party/android_deps/libs/org_tensorflow_tensorflow_lite_api/LICENSE
  - https://chromium-review.googlesource.com/c/chromium/src/+/5494530

Updated licenses:
  * third_party/android_deps/libs/com_google_android_gms_play_services_location/LICENSE
  - https://chromium-review.googlesource.com/c/chromium/src/+/5515920

  * third_party/ffmpeg/CREDITS.chromium
  - https://chromium.googlesource.com/chromium/third_party/ffmpeg.git/+/46a49cb3ec46cf95499c7f265e9d840c16430ac7

  * third_party/swiftshader/third_party/SPIRV-Headers/LICENSE
  - https://swiftshader-review.googlesource.com/c/SwiftShader/+/73371

Test-built (big thanks to @rjanani-p):
--------------------------------------

* chromium-ozone-wayland:
 - master, clang,    MACHINE=qemux86-64
 - scarthgap, clang, MACHINE=qemuarm64, qemux86-64

* chromium-x11:
 - master, clang,    MACHINE=qemuarm, qemuarm64, qemux86-64, raspberrypi4-64
 - scarthgap, clang, MACHINE=qemuarm, qemuarm64, qemux86-64, raspberrypi4-64

### CODE REVIEW

**Comment by MaxIhlenfeldt** [comment]
@rjanani-p as always, testing would be greatly appreciated!

**Comment by rjanani-p** [comment]
> @rjanani-p as always, testing would be greatly appreciated!

sure, I will start testing. Thank you.

**Comment by rjanani-p** [comment]
@MaxIhlenfeldt , I have completed the testing for below configuration for Poky master with latest changes, sharing the results for reference:

1.For chromium-x11 & qemux86-64 target: compiled successfully without build issues, able to check chromium version using qemux86-64 emulator

2.For chromium-x11 & qemuarm target: compiled successfully without build issues, to check chromium version using qemuarm emulator unable to check it due to curser / mouse is not working properly while operating with chromium browser

3.For chromium-x11 & qemuarm64 target: compiled successfully without build issues, able to check chromium version using qemuarm64 emulator

4. For chromium-x11 & raspberrypi4-64 target: compiled successfully without build issues, didn't check with hardware due to hardware unavailability.

5. For chromium-ozone-wayland & qemux86-64 target: compiled successfully without build issues, able to check chromium version using qemux86-64 emulator

I will start testing for poky scarthgap branch. Thank you.

**Comment by rjanani-p** [comment]
@MaxIhlenfeldt , I have completed the testing for below configuration for Poky Scarthgap with latest changes, sharing the results for reference:
1.For chromium-x11 & qemux86-64 target: compiled successfully without build issues, able to check chromium version using qemux86-64 emulator

2.For chromium-x11 & qemuarm target: compiled successfully without build issues, to check chromium version using qemuarm emulator unable to check it due to curser / mouse is not working properly while operating with chromium browser

3.For chromium-x11 & qemuarm64 target: compiled successfully without build issues, able to check chromium version using qemuarm64 emulator

4.For chromium-x11 & raspberrypi4-64 target: compiled successfully without build issues, didn't check with hardware due to hardware unavailability.

5.For chromium-ozone-wayland & qemux86-64 target: compiled successfully without build issues, able to check chromium version using qemux86-64 emulator

**Comment by MaxIhlenfeldt** [comment]
Thanks for the testing! The commit message and PR description are already up to date, once @rakuco approves we can merge this.

**Review by rakuco — APPROVED** [review]
lgtm! I can't even remember the last time we didn't need any backports!

**Comment by SoumyaWind** [comment]
@rjanani-p

**Comment by rjanani-p** [comment]
Hi @MaxIhlenfeldt @rakuco 
cc: @rwmacleod 
I am leaving WindRiver due to my ML leave and from now on words @SoumyaWind will support you temporarily for all the new Chromium PR testing .
It was great working with all and thanks for all your support!!

**Comment by rakuco** [comment]
Thank you, @rjanani-p, and welcome, @SoumyaWind!

**Pull request merged**
