### PR TITLE
[WIP] Update firefox to 60esr

### PR DESCRIPTION
**Pull request by ashie**
Still work in progress.

TODO list to complete this pull request (From #128):

* [x] please rebase this PR on top of our master branch
* [x] squash the commits in a logical patchset
* [ ] finish the PR work for meta-rust/meta-rust#191
* [x] Remove some evil patches
* [x] Import Debian's patch set as usual
* [x] Upgrade firefox-l10n too
* [x] Fix build error of firefox-l10n
* [x] Add a patch to avoid running autoconf-2.13
* [x] Add README

### CODE REVIEW

**Comment by ashie** [comment]
> Please rebase this as some parts are in conflict with master

Done.
And removed some needless & confusing code form mozilla.bbclass & mozconfig.

**Comment by otavio** [comment]
@ashie what is still holding it to be finished? It'd be awesome to have it merged.

**Comment by ashie** [comment]
> @ashie what is still holding it to be finished? It'd be awesome to have it merged.

Please see https://github.com/meta-rust/meta-rust/pull/208

**Comment by ashie** [comment]
Follow #177

**Comment by kraj** [comment]
@otavio can we merge this PR

**Comment by otavio** [comment]
@ashie thanks for working on this. It'd be awesome if you could keep an eye on this and provide updates and testing :+1:

**Pull request merged**
