### PR TITLE
Update firefox 45esr

### PR DESCRIPTION
**Pull request by geiseri**
This updates the Firefox browser recipe to 45.5.1 esr along with the Debian patch set from their git repo.  It has been tested for building with krogoth only so far.  It should not have a problem with morty or master though.

### CODE REVIEW

**Comment by otavio** [comment]
@fbertux please give this a try on morty and master. If it goes fine we can merge it.

**Comment by fbertux** [comment]
Hi @geiseri 

Firefox it's failing with error:

`ERROR: firefox-45.5.1esr-r0 do_package_qa: QA Issue: No GNU_HASH in the elf binary: '../build/tmp/work/armv5e-oel-linux-gnueabi/firefox/45.5.1esr-r0/packages-split/firefox/usr/lib/firefox/libnss3.so'
No GNU_HASH in the elf binary: '../build/tmp/work/armv5e-oel-linux-gnueabi/firefox/45.5.1esr-r0/packages-split/firefox/usr/lib/firefox/libsmime3.so'
No GNU_HASH in the elf binary: '../build/tmp/work/armv5e-oel-linux-gnueabi/firefox/45.5.1esr-r0/packages-split/firefox/usr/lib/firefox/libnssdbm3.so'
No GNU_HASH in the elf binary: '../build/tmp/work/armv5e-oel-linux-gnueabi/firefox/45.5.1esr-r0/packages-split/firefox/usr/lib/firefox/libnssckbi.so'
No GNU_HASH in the elf binary: '../build/tmp/work/armv5e-oel-linux-gnueabi/firefox/45.5.1esr-r0/packages-split/firefox/usr/lib/firefox/libssl3.so'
No GNU_HASH in the elf binary: '../build/tmp/work/armv5e-oel-linux-gnueabi/firefox/45.5.1esr-r0/packages-split/firefox/usr/lib/firefox/libfreebl3.so'
No GNU_HASH in the elf binary: '../build/tmp/work/armv5e-oel-linux-gnueabi/firefox/45.5.1esr-r0/packages-split/firefox/usr/lib/firefox/libnssutil3.so'
No GNU_HASH in the elf binary: '../build/tmp/work/armv5e-oel-linux-gnueabi/firefox/45.5.1esr-r0/packages-split/firefox/usr/lib/firefox/libsoftokn3.so' [ldflags]
ERROR: firefox-45.5.1esr-r0 do_package_qa: QA run found fatal errors. Please consider fixing them.
ERROR: firefox-45.5.1esr-r0 do_package_qa: Function failed: do_package_qa`

This error appears in both master and morty, you need to fix LDFLAGS using something like:

`TARGET_CC_ARCH += "${LDFLAGS}"`

**Comment by geiseri** [comment]
Let me give that a try.  Is this only on ARM, or x86 too?

**Comment by fbertux** [comment]
I tested only with arm. Yes, I can test these patches.

**Comment by geiseri** [comment]
@fbertux okay, I pushed it with the fix.  Let me know how it works out.  Thanks!

**Comment by otavio** [comment]
The patchset is fine however it has some pending actions before we merge it, those are:

- squash the commits on a single commit as this is all related and should be merged together
- fix the commit log to follow the guidelines (http://www.openembedded.org/wiki/How_to_submit_a_patch_to_OpenEmbedded#Committing_your_patch)

Once those are done, we can merge it.

**Comment by geiseri** [comment]
Will do!

**Comment by geiseri** [comment]
@otavio I think I got a conflict because there was a merge in my history.  Do you have a suggestion on how to remove it?

**Comment by otavio** [comment]
Rebase it on top of current master.

**Comment by geiseri** [comment]
@otavio done!

**Comment by geiseri** [comment]
@otavio i updated the log message, was there anything more?

**Pull request merged**
