### PR TITLE
chromium: Backport upstream patch to fix the build with LLVM 12 and later

### LINKED ISSUE #461: chromium-88.0.4324.150 fails to build with LLVM 12
Using LLVM 12 from https://github.com/yoedistro/meta-clang/tree/yoe/mut makes the Chromium fail with
```
| ../../third_party/blink/renderer/platform/disk_data_allocator.cc:66:10: error: call to deleted constructor of 'blink::DiskDataMetadata'
|   return chosen_chunk;
|          ^~~~~~~~~~~~
| ../../third_party/blink/renderer/platform/disk_data_metadata.h:17:3: note: 'DiskDataMetadata' has been explicitly marked deleted here
|   DiskDataMetadata(DiskDataMetadata&& other) = delete;
|   ^
| 1 error generated.
```
The same Chromium version builds with LLVM 11 from https://github.com/kraj/meta-clang master branch.
Does anyone know what's going on? Did LLVM 12 become stricter or is it faulty?

### PR DESCRIPTION
**Pull request by rakuco**
Thanks to Zoltán Böszörményi for pointing to the upstream fix.

Fixes #461.

### CODE REVIEW

**Comment by rakuco** [comment]
@zboszor can you check if this fixes your build?

**Comment by zboszor** [comment]
The build is in progress on my side with the patch applied in my layer in a bbappend, I will report back in a few hours.

**Comment by zboszor** [comment]
Yes, this patch does fix the build error with LLVM 12.

**Review by kraj — APPROVED** [review]
lgtm

**Comment by rakuco** [comment]
Thanks for checking, @zboszor!

**Pull request merged**
