### PR TITLE
Ease chromium-wayland build

### PR DESCRIPTION
**Pull request by jaragunde**
This set of patches simplifies the build of chromium-wayland, removing the need for users to set the CHROMIUM_ENABLE_WAYLAND flag. The flag will be set by the recipe.

[note: I first sent the patches via the openembedded ML, this is the latest version of the patches after the feedback received there. I'm opening this PR in case it's more convenient for maintainers, feel free to close if you prefer the other way!]

### CODE REVIEW

**Comment by shr-project** [comment]
Review on ML is preferred to github's PRs which are useless for review (not your fault)

**Comment by jaragunde** [comment]
Alright! Patches were sent to openembedded-devel anyway some days ago: http://lists.openembedded.org/pipermail/openembedded-devel/2016-November/109917.html

**Comment by otavio** [comment]
The commit log is not following the guidelines, please fix.

**Comment by jaragunde** [comment]
Hello again, and happy new year! I've re-sent the patches to the list, adding the `chromium` or `chromium-wayland` prefixes to the commit log.

**Comment by jaragunde** [comment]
Hi! Updated patches are available in the mailing list and in this PR. Could you please take another look? I've been working to update the chromium-wayland to a newer version and I'll be able to send it soon, but I'm building on top of these patches :-)

**Comment by otavio** [comment]
We merged those yesterday, please rebase and see if something is missing.

**Comment by jaragunde** [comment]
Thank you very much!

**Pull request closed without merging**
