### PR TITLE
chromium: update to 96.0.4664.110

### PR DESCRIPTION
**Pull request by rwmacleod**
https://chromereleases.googleblog.com/2021/12/stable-channel-update-for-desktop_13.html

Test-built with:
  * chromium-x11
    * master,  clang, MACHINE="qemux86-64,qemuarm64"

Signed-off-by: Randy MacLeod <Randy.MacLeod@windriver.com>

### CODE REVIEW

**Comment by kraj** [comment]
Thanks @rwmacleod  Can you check with TCLIBC = "musl" as well ? atleast `bitbake -cpatch`

**Comment by msisov** [comment]
Triggered the bots.

**Comment by rwmacleod** [comment]
I thought it was a very minor update so I didn't think about testing musl. It turns out that third_party/quiche was updated so one of the musl patches can be dropped. With that change, it patches cleanly and I'm building now. Update or additional patch coming soon.

**Comment by rwmacleod** [comment]
New PR  https://github.com/OSSystems/meta-browser/pull/596 that drops a patch for musl submitted so closing this one.

**Pull request closed without merging**
