### PR TITLE
Two build fixes for chromium

### PR DESCRIPTION
**Pull request by schnitzeltony**

### CODE REVIEW

**Comment by kraj** [comment]
first commit to fix type is good to go. But I am not sure about second commit, we explicitly changed to use libc++ for native and target portions of chromium build. So I think this patch should no  longer be needed.

**Comment by schnitzeltony** [comment]
> But I am not sure about second commit, we explicitly changed to use libc++ for native and target portions of chromium build. So I think this patch should no longer be needed.

Am on very current master on all layers and got error mentioned in additional patch comment. With second patch added, build passes.

**Comment by kraj** [comment]
> > But I am not sure about second commit, we explicitly changed to use libc++ for native and target portions of chromium build. So I think this patch should no longer be needed.
> 
> Am on very current master on all layers and got error mentioned in additional patch comment. With second patch added, build passes.

master of meta-browser I guess, but which release are you on for oe-core/meta-clang

**Comment by schnitzeltony** [comment]
**All** layers are latest master / meta-clang's top commit is 45a3707291a4e8bd2469b0d2bb9cf9e07878ae08 (the latest I can get)

**Comment by schnitzeltony** [comment]
Thanks Khem for taking care of first patch.

After recent upgrade to 92.0.4515.131 build fails on other places with same libstdc++ related error as described in second patch.

So I looked around a bit and found in log.do_compile many lines as:

> clang-13: warning: argument unused during compilation: '-stdlib=libc++' [-Wunused-command-line-argument]

Maybe we are not doing what we intend to do?

**Comment by schnitzeltony** [comment]
Interesting:

> bitbake -e | grep ^BASE_DEFAULT_DEPS
> BASE_DEFAULT_DEPS="virtual/aarch64-mortsgna-linux-gcc virtual/aarch64-mortsgna-linux-compilerlibs virtual/libc"
> BASE_DEFAULT_DEPS:toolchain-clang=" clang-cross-aarch64 virtual/libc  libgcc  virtual/aarch64-mortsgna-linux-compilerlibs "
> BASE_DEFAULT_DEPS:toolchain-clang:class-target=" clang-cross-aarch64 virtual/libc  libgcc  virtual/aarch64-mortsgna-linux-compilerlibs "
> 

looking into clang.bbclas I'd expect at least  `compiler-rt libcxx`. Suggestions?

**Comment by schnitzeltony** [comment]
Aargh: Forgot chromium-x11:

> bitbake -e chromium-x11 | grep ^BASE_DEFAULT_DEPS
> BASE_DEFAULT_DEPS=" clang-cross-aarch64 virtual/libc  compiler-rt libcxx libcxx"
> BASE_DEFAULT_DEPS:toolchain-clang=" clang-cross-aarch64 virtual/libc  compiler-rt libcxx libcxx"
> BASE_DEFAULT_DEPS:toolchain-clang:class-target=" clang-cross-aarch64 virtual/libc  compiler-rt libcxx libcxx"

Look more as expected. So still why all these `unused during compilation: '-stdlib=libc++'`  warnings?

**Comment by kraj** [comment]
> Thanks Khem for taking care of first patch.
> 
> After recent upgrade to 92.0.4515.131 build fails on other places with same libstdc++ related error as described in second patch.
> 
> So I looked around a bit and found in log.do_compile many lines as:
> 
> > clang-13: warning: argument unused during compilation: '-stdlib=libc++' [-Wunused-command-line-argument]
> 
> Maybe we are not doing what we intend to do?

are you using distcc by any chance ? you could be hitting
https://github.com/distcc/distcc/issues/329

**Comment by schnitzeltony** [comment]
> are you using distcc by any chance ? you could be hitting
No - and off topic read mortsgna from back to front...

**Comment by kraj** [comment]
> > are you using distcc by any chance ? you could be hitting
> 
> No - and off topic read mortsgna from back to front...

OMG !! I thought iti was some brewery name :)

**Pull request closed without merging**
