### PR TITLE
Firefox ESR to 38.8.0esr (2016-04-26)

### PR DESCRIPTION
**Pull request by WarheadsSE**
Update firefox and all l10n recipes to 38.8.0 as released on 26 April 2016.

https://www.mozilla.org/en-US/firefox/38.8.0/releasenotes/
https://www.mozilla.org/en-US/security/known-vulnerabilities/firefox-esr/#firefoxesr38.8

### CODE REVIEW

**Comment by fbertux** [comment]
Did you build using master branch and GCC 6?

**Comment by WarheadsSE** [comment]
I have not because we ($dayjob) don't have a build tree against master at the moment. This has been tested against dora, jethro, krogoth

**Comment by fbertux** [comment]
Ahh ok, 
I fixed GCC 6 build on master.

**Comment by WarheadsSE** [comment]
Per discussion with @otavio , I will begin work on the FF 45.x ESR in a few weeks.

**Comment by WarheadsSE** [comment]
@fbertux I look forward to not having to bbappend the PNBLACKLIST away :+1:

**Comment by fbertux** [comment]
@WarheadsSE I sent a patch to ML with a correction. http://lists.openembedded.org/pipermail/openembedded-devel/2016-July/108029.html

**Pull request merged**
