### PR TITLE
chromium: Update README and dependencies for kirkstone

### PR DESCRIPTION
**Pull request by MaxIhlenfeldt**
See the discussion in https://github.com/OSSystems/meta-browser/issues/789.

### CODE REVIEW

**Comment by MaxIhlenfeldt** [comment]
I've done a test build for `raspberrypi4-64` which worked, I suppose that should be enough.

**Review by rakuco — APPROVED** [review]
lgtm

**Comment by Himaniyocto** [comment]
@MaxIhlenfeldt I encountered an issue when cloning the repository. The error message I received is:
ERROR: Layer chromium-browser-layer is not compatible with the core layer which only supports these series: kirkstone (layer is compatible with scarthgap).
Could you please confirm if this branch is intended for the Kirkstone series? Any assistance on resolving this compatibility issue would be greatly appreciated.

Thank you!

**Comment by MaxIhlenfeldt** [comment]
@Himaniyocto the `kirkstone` branch of meta-browser should be compatible with kirkstone as per https://github.com/OSSystems/meta-browser/blob/kirkstone/meta-chromium/conf/layer.conf#L12.

**Comment by Himaniyocto** [comment]
> @Himaniyocto the `kirkstone` branch of meta-browser should be compatible with kirkstone as per https://github.com/OSSystems/meta-browser/blob/kirkstone/meta-chromium/conf/layer.conf#L12.

Hello @MaxIhlenfeldt  i am getting error after cloning this repo as  for meta -clang layer as i added in bblayers.conf  


can you please guide where i can get meta-clang

**Comment by MaxIhlenfeldt** [comment]
> can you please guide where i can get meta-clang

@Himaniyocto the repo is hosted at https://github.com/kraj/meta-clang. Note that you also need a checkout of meta-lts-mixins' `kirkstone/rust-1.70` branch (https://git.yoctoproject.org/meta-lts-mixins/log/?h=kirkstone/rust-1.70).

**Pull request merged**
