### PR TITLE
chromium: update to 98.0.4758.102

### PR DESCRIPTION
**Pull request by msisov**
Release notes -
https://chromereleases.googleblog.com/2022/02/stable-channel-update-for-desktop_14.html

License changes:
---------------

Added licences:
  * third_party/android_deps/libs/com_google_flatbuffers_flatbuffers_java/LICENSE
  - Actually add flatbuffers to //third_party/android_deps
  - https://chromium-review.googlesource.com/c/chromium/src/+/3272235

  * third_party/rjsmin/LICENSE
  - Check in third_party/rjsmin
  - https://chromium-review.googlesource.com/c/chromium/src/+/3314897

  * tools/mac/power/protos/third_party/pprof/LICENSE
  - [battery]: Add pprof proto definition.
  - https://chromium-review.googlesource.com/c/chromium/src/+/3296463

Updated licenses:
  * third_party/dawn/LICENSE
  - Roll Dawn from 3b06c01bbb43 to 1b1b658d3655 (3 revisions)
  - https://chromium-review.googlesource.com/c/chromium/src/+/3328447

  * third_party/icu/LICENSE
  - Roll ICU
  - https://chromium-review.googlesource.com/c/chromium/src/+/3309670

Removed licenses:
  * third_party/tlslite/LICENSE
  - Remove third_party/tlslite and SpawnedTestServer::TYPE_HTTPS
  - https://chromium-review.googlesource.com/c/chromium/src/+/3286767

---------------

Test-built with:
* chromium-ozone-wayland:
  * honister,  clang, MACHINE="intel-corei7-64"
  * honister,  clang, MACHINE="raspberrypi3
  * hardknott, clang, MACHINE="raspberrypi3
  * dunfell, clang**, MACHINE="qemuarm64"

* chromium-x11
  * honister,  clang, MACHINE="raspberrypi3"
  * hardknott, clang, MACHINE="raspberrypi3"
  * dunfell, clang**, MACHINE="raspberrypi3"

** Please note that Chromium requires clang version to be >= 12.
For that, when on dunfell branch, use meta-clang/clang12 branch.

### CODE REVIEW

**Comment by msisov** [comment]
Please ignore for now. That's in process of testing

**Comment by msisov** [comment]
please review

**Review by rakuco — APPROVED** [review]
lgtm! this update looks fairly non-controversial, I like that :-)

**Review by kraj — COMMENTED** [review]
I will stage it for a musl build.

**Comment by rwmacleod** [comment]
This was merged with the "WIP:" prefix when it seems that it's fine. 
That's going to confuse people, I expect. Should head be reset before more people notice or do we just live with the misleading prefix?

**Comment by kraj** [comment]
I think we should mark pulls as `WIP` when they are in progress, that way it wont be merged until intentionally changed to `ready`

**Comment by rwmacleod** [comment]
@kraj  Isn't that what the *master-next* branch is for? I feels like i missed something here. This commit has been merged to the *master* branch so it shouldn't have the WIP prefix. 

By the way, it builds for qemu-x86-64 and rpi4 for me on our internal hardknott branch.

**Comment by kraj** [comment]
> @kraj Isn't that what the _master-next_ branch is for? I feels like i missed something here. This commit has been merged to the _master_ branch so it shouldn't have the WIP prefix.
> 
> By the way, it builds for qemu-x86-64 and rpi4 for me on our internal hardknott branch.

Master-next is not needed on GitHub like workflows where unit of commit is a pull request it works for old style git workflows where someone is beaming patches from mailing list etc into a staging area

**Comment by msisov** [comment]
> This was merged with the "WIP:" prefix when it seems that it's fine. That's going to confuse people, I expect. Should head be reset before more people notice or do we just live with the misleading prefix?

right. I forgot to remove that :facepalm:

**Comment by rakuco** [comment]
> That's going to confuse people, I expect. Should head be reset before more people notice or do we just live with the misleading prefix?

Thanks for noticing and sorry that we overlooked this one. I think force-pushing will cause even more headache than just letting this one pass, so I'm afraid we'll just have to live with it :/

**Comment by msisov** [comment]
Nevertheless, I'm in the process of update the meta-browser to M99.

**Comment by kraj** [comment]
> > That's going to confuse people, I expect. Should head be reset before more people notice or do we just live with the misleading prefix?
> 
> Thanks for noticing and sorry that we overlooked this one. I think force-pushing will cause even more headache than just letting this one pass, so I'm afraid we'll just have to live with it :/

yes its completely ok.

**Pull request merged**
