### PR TITLE
[scarthgap] chromium: Use correct Rust mixin layer dependency

### LINKED ISSUE #862: Scarthgap meta-lts-mixins layer dependency name
Copying https://github.com/OSSystems/meta-browser/pull/860#issuecomment-2549549730 from @darren-etheridge here:

I had to change the layer dependency name on the scarthgap branch like this:

```
diff --cc meta-chromium/conf/layer.conf
index 48c22a5,48c22a5..9537220
--- a/meta-chromium/conf/layer.conf
+++ b/meta-chromium/conf/layer.conf
@@@ -11,4 -11,4 +11,4 @@@ BBFILE_PRIORITY_chromium-browser-layer 
  LAYERVERSION_chromium-browser-layer = "1"
  LAYERSERIES_COMPAT_chromium-browser-layer = "scarthgap styhead walnascar"
  
--LAYERDEPENDS_chromium-browser-layer = "clang-layer core openembedded-layer lts-rust-mixin"
++LAYERDEPENDS_chromium-browser-layer = "clang-layer core openembedded-layer scarthgap-rust-mixin"

```

Looks like the lts-rust-mixin layer name is only used in the Kirkstone branch of meta-lts-mixin and not scarthgap.  Is this something I am doing wrong or is this a fix needed in your scarthgap branch of meta-chromium?

Seems to be defined in this file, on scarthgap/rust branch.
https://git.yoctoproject.org/meta-lts-mixins/tree/conf/layer.conf?h=scarthgap/rust

Once I did this Chromium v131 is working fine on the Texas Instruments scarthgap yocto with GPU acceleration.

### PR DESCRIPTION
**Pull request by MaxIhlenfeldt**
Fixes #862.

Thanks to @darren-etheridge for finding this as well as the right name to use!

### CODE REVIEW

**Review by rakuco — APPROVED** [review]

**Comment by bkauler** [comment]
@MaxIhlenfeldt 
Note that I downloaded from your 131.0.6778.139-scarthgap branch a couple of days ago:

`git clone -b 131.0.6778.139-scarthgap https://github.com/MaxIhlenfeldt/meta-browser meta-chromium --depth 1`

And I had to manually fix meta-lts-mixins/conf/layer.conf, change "lts-rust-mixin" to "scarthgap-rust-mixin".

And then success, chromium-x11 compiled!

**Comment by MaxIhlenfeldt** [comment]
@bkauler are you sure you cloned the `scarthgap/rust` branch of meta-lts-mixins? The command you pasted should do that, but looking at https://git.yoctoproject.org/meta-lts-mixins/tree/conf/layer.conf?h=scarthgap/rust I don't see any occurrences of `lts-rust-mixin`, everything is using `scarthgap-rust-mixin` already.

**Comment by bkauler** [comment]
Max,
Yes, but your branch "131.0.6778.139-scarthgap" at MaxIhlenfeldt/meta-browser hasn't been updated. That's where I got meta-browser from, not from OSSystems.

**Comment by MaxIhlenfeldt** [comment]
My fork is not meant to be used for anything else than development, please use https://github.com/OSSystems/meta-browser/tree/scarthgap.

**Comment by bkauler** [comment]
OK

**Pull request merged**
