### PR TITLE
Fix checksums missed in Firefox 38.6.1esr update.

### PR DESCRIPTION
**Pull request by WarheadsSE**
As the title says. A little embarrassed that I missed this.

### CODE REVIEW

**Comment by shr-project** [comment]
This actually breaks the checksums

firefox-l10n-pl: Check if the license information has changed in /home/jenkins/oe/world/shr-core/openembedded-core/LICENSE to verify that the LICENSE value "MPLv1 | GPLv2+ | LGPLv2.1+" remains valid [license-checksum]

Are you building it with some very old oe-core? IIRC the LICENSE files were updated before Dizzy release.

**Comment by WarheadsSE** [comment]
Yeah, this one is my bad. It needs reverted on master.

Jason Plum
WarheadsSE

**Comment by otavio** [comment]
@shr-project as you have commit, can you handle the revert please? I am under heavy load here.

**Comment by shr-project** [comment]
I've already reverted it (Just after WarheadsSE's message).

**Pull request merged**
