### PR TITLE
chromium: Drop scoped file patch

### PR DESCRIPTION
**Pull request by kraj**
This patch is no longer needed with 116

### CODE REVIEW

**Review by rakuco — APPROVED** [review]
lgtm

**Comment by ibenhassen** [comment]
Hi @kraj ,
Did you try to build chromium with musl after making this change ?
Thanks

**Comment by kraj** [comment]
> Hi @kraj ,
> Did you try to build chromium with musl after making this change ?
> I've removed me too last week but it didn't build successfully , it is blocked at 96%.(with mksnaphot build issue)
> Thanks

It builds fine here with master branches

**Comment by ibenhassen** [comment]
@kraj Thanks, I'm using dunfellclang14 for clang , nodjs 14 and master for meta-browser and I got an issue like this: 
[58810/61094] "python3" "../../build/toolchain/gcc_link_wrapper.py" --output="./mksnapshot" -- arm-hdl-linux-musleabi-clang++ -target arm-hdl-linux-musleabi   -mfpu=neon -mfloat-abi=hard -mcpu=cortex-a7 -mlittle-endian -Qunused-arguments --sysroot=/home/ibenhassen/projects/EG4/eg4-chromium-musl/build/tmp-musl/work/cortexa7t2hf-neon-mx7d-hdl-linux-musleabi/chromium-ozone-wayland/116.0.5845.179-r0-hdl1/recipe-sysroot -pie -fuse-ld=lld -Wl,--fatal-warnings -Wl,--build-id=sha1 -fPIC -Wl,-z,noexecstack -Wl,-z,relro -Wl,-z,now -Wl,--icf=all -Wl,--color-diagnostics -Wl,-mllvm,-instcombine-lower-dbg-declare=0 -flto=thin -Wl,--thinlto-jobs=96 -Wl,--thinlto-cache-dir=thinlto-cache -Wl,--thinlto-cache-policy=cache_size=10\%:cache_size_bytes=40g:cache_size_files=100000 -Wl,-mllvm,-import-instr-limit=30 -fwhole-program-vtables -march=armv7-a -Wl,--undefined-version -Wl,--no-call-graph-profile-sort -rdynamic -Wl,-z,defs -Wl,--as-needed -Wl,--lto-O0 -pie -Wl,--disable-new-dtags -Wl,-O2 -Wl,--gc-sections -Wl,-O1 -Wl,--hash-style=gnu -Wl,--as-needed  -stdlib=libc++ -lexecinfo -o "./mksnapshot" -Wl,--start-group @"./mksnapshot.rsp"  -Wl,--end-group  -latomic -ldl -lpthread -lrt

 

Currently  1 running tasks (2027 of 2027)  99% |######################################################################################################################################################################################################################################## |
0: chromium-ozone-wayland-116.0.5845.179-r0-hdl1 do_compile (pid 3584303)  96%

Any help please?

**Pull request merged**
