### PR TITLE
chromium: update to 119.0.6045.159

### PR DESCRIPTION
**Pull request by MaxIhlenfeldt**
Release notes:
    https://chromereleases.googleblog.com/2023/10/stable-channel-update-for-desktop_31.html
    https://chromereleases.googleblog.com/2023/11/stable-channel-update-for-desktop.html
    https://chromereleases.googleblog.com/2023/11/stable-channel-update-for-desktop_14.html

Build and patch changes:
------------------------

Drop five backported patches that are included upstream now, and add four new
backports.

Add more fixes to 0017-Avoid-parenthesized-initialization-of-aggregates.patch.

Add 0021-Don-t-delete-CrashKeyWithName-dtor.patch to fix a build error
on older versions of clang (on mickledore, kirkstone, and dunfell).

Rebase remaining patches.

License changes:
----------------

Added licenses:
  * third_party/android_deps/libs/com_google_auto_service_auto_service_annotations/LICENSE
  - https://chromium-review.googlesource.com/c/chromium/src/+/4887649

  * third_party/jszip/LICENSE
  - https://chromium-review.googlesource.com/c/chromium/src/+/4793948

  * third_party/wayland-protocols/gtk/COPYING,
    third_party/wayland-protocols/kde/COPYING.LIB
  - https://chromium-review.googlesource.com/c/chromium/src/+/4845816

Removed licenses:
  * third_party/android_deps/libs/android_arch_lifecycle_common_java8/LICENSE,
    third_party/android_deps/libs/com_android_support_animated_vector_drawable/LICENSE,
    third_party/android_deps/libs/com_android_support_appcompat_v7/LICENSE,
    third_party/android_deps/libs/com_android_support_cardview_v7/LICENSE,
    third_party/android_deps/libs/com_android_support_design/LICENSE,
    third_party/android_deps/libs/com_android_support_multidex/LICENSE,
    third_party/android_deps/libs/com_android_support_recyclerview_v7/LICENSE,
    third_party/android_deps/libs/com_android_support_support_fragment/LICENSE,
    third_party/android_deps/libs/com_android_support_support_media_compat/LICENSE,
    third_party/android_deps/libs/com_android_support_support_v4/LICENSE,
    third_party/android_deps/libs/com_android_support_support_vector_drawable/LICENSE,
    third_party/android_deps/libs/com_android_support_transition/LICENSE
  - https://chromium-review.googlesource.com/c/chromium/src/+/4904153

Updated licenses: none.

Test-built (big thanks to @nrpt-m):
-----------------------------------

* chromium-ozone-wayland:
 - master, clang,     MACHINE=qemux86-64
 - mickledore, clang, MACHINE=qemuarm64, qemux86-64
 - kirkstone, clang,  MACHINE=qemux86-64, raspberrypi4-64
 - dunfell, clang**,  MACHINE=qemux86-64

* chromium-x11
 - master, clang,     MACHINE=qemux86-64, qemuarm, qemuarm64, raspberrypi4-64
 - mickledore, clang, MACHINE=qemux86-64, qemuarm, qemuarm64, raspberrypi4-64
 - kirkstone, clang,  MACHINE=qemux86-64, qemuarm, qemuarm64, raspberrypi4-64
 - dunfell, clang**,  MACHINE=qemux86-64, qemuarm, qemuarm64, raspberrypi4-64***

** Please note that Chromium requires below set-up when on dunfell
branch.
 - The clang version to be >= 14 and for that, use the latest
   meta-clang/dunfell-clang14 branch.
 - Require the latest meta-oe with Nodejs 14.x support.
 - Add the PREFERRED_VERSION_nodejs-native = "14.%" in conf/local.conf
   file.

*** Please note that there currently is a problem on RPi4/dunfell where
Chromium crashes because of an illegal instruction error.

Signed-off-by: Max Ihlenfeldt <max@igalia.com>

### CODE REVIEW

**Comment by MaxIhlenfeldt** [comment]
@nrpt-m as always, testing would be greatly appreciated! Like in the last PR, I already included the test results in the changelog's "Test-built" section. I'll check again that it's correct once the testing is finished.

**Review by rakuco — APPROVED** [review]
lgtm!

**Comment by MaxIhlenfeldt** [comment]
This should be fixed by https://chromium-review.googlesource.com/c/chromium/src/+/5001687. Give me a moment to create a backport.

**Comment by MaxIhlenfeldt** [comment]
@nrpt-m please try again with the latest revision.

**Comment by nrpt-m** [comment]
> @nrpt-m please try again with the latest revision.

Thanks, it started compiling now ;-)

**Comment by kraj** [comment]
I have built and run it on musl system 
```
chromium-ozone-wayland:
master, clang, musl, MACHINE=qemux86-64
```

**Review by kraj — APPROVED** [review]
lgtm

**Comment by nrpt-m** [comment]
@MaxIhlenfeldt @rakuco ,
Have completed the builds & testing in master branch for all these below systems and chromium worked well in all these systems.

- chromium-ozone-wayland: qemux86-64

- chromium-x11: qemux86-64, qemuarm*, qemuarm64, raspberrypi4-64*

qemuarm* :- Have again observed same messages as with 118 on console while running chromium but, chromium works fine.

> [  203.896427] Alignment trap: chromium-bin (858) PC=0x07e6e40e Instr=0xe950a301 Address=0x57378592 FSR 0x221
> [  203.896763] Alignment trap: chromium-bin (858) PC=0x07e6e40e Instr=0xe950a301 Address=0x5737859a FSR 0x221
> [  203.897181] Alignment trap: chromium-bin (858) PC=0x07e6e40e Instr=0xe950a301 Address=0x573785a2 FSR 0x221
> [  203.897601] Alignment trap: chromium-bin (858) PC=0x07e6e40e Instr=0xe950a301 Address=0x573785aa FSR 0x221
> [  203.898061] Alignment trap: chromium-bin (858) PC=0x07e6e40e Instr=0xe950a301 Address=0x573785b2 FSR 0x221
> [  203.898723] Alignment trap: chromium-bin (858) PC=0x07e6e40e Instr=0xe950a301 Address=0x573785ba FSR 0x221
> root@qemuarm:~#

raspberrypi4-64* :- Chromium works fine but, @rwmacleod has observed that while running youtube in chromium audio is not coming. Let us know your thought on this as Audio used to work before.

**Comment by nrpt-m** [comment]
@MaxIhlenfeldt @rakuco,
Have completed the builds & testing in kirkstone branch for all these below systems and chromium worked well in all these systems.

- chromium-ozone-wayland: qemux86-64

- chromium-x11: qemux86-64, qemuarm, qemuarm64, raspberrypi4-64

Next is dunfell and mickledore branches.

**Comment by nrpt-m** [comment]
@MaxIhlenfeldt @rakuco
Have completed the builds & testing in mickledore branch for all these below systems and chromium worked well in all these systems.

- chromium-ozone-wayland: qemux86-64

- chromium-x11: qemux86-64, qemuarm, qemuarm64, raspberrypi4-64**

raspberrypi4-64**:-  Chromium works fine but, @rwmacleod has observed that while running youtube in chromium audio is not coming same as with master branch. Have attached the logs.
[Chromium-119-rpi4-mickledore.log](https://github.com/OSSystems/meta-browser/files/13394284/Chromium-119-rpi4-mickledore.log)

**Comment by nrpt-m** [comment]
> Sounds to me like this is caused by something else, and not Chromium, could that be?

May be but, it used to work earlier as @rwmacleod said.

**Comment by nrpt-m** [comment]
@MaxIhlenfeldt @rakuco
Have completed the builds & testing in dunfell branch for all these below systems and chromium worked well in all these systems.

- chromium-ozone-wayland: qemux86-64

- chromium-x11: qemux86-64, qemuarm, qemuarm64, raspberrypi4-64**

raspberrypi4-64**:- Have observed again the illegal instruction error with chromium-119 as well. Have attached the console logs. Downloading coredump chromium-bin file, will share you the links once uploaded.
[chromium-119-rpi4-dunfell-console-logs.txt](https://github.com/OSSystems/meta-browser/files/13394825/chromium-119-rpi4-dunfell-console-logs.txt)

**Comment by marex** [comment]
It seems since about v110, the GPU process crashes with error 5 on MX8M with etnaviv driver and weston compositor, and Chromium works only with software rendering.

**Comment by rwmacleod** [comment]
> > Sounds to me like this is caused by something else, and not Chromium, could that be?
> 
> May be but, it used to work earlier as @rwmacleod said.

I suspect that audio will work with the XFCE desktop as a non root user. @nrpt-m said that he'd check when testing this update with WR Linux once 119 is merged if no one gets there earlier.

**Comment by nrpt-m** [comment]
> Thanks for the testing! I'll merge this now, and then @nrpt-m can verify audio (hopefully) still works and we can take a closer look at the illegal instruction error.

@MaxIhlenfeldt ,
We have verified the audio while running youtube in chromium with rpi4/Mickledore image and it works fine.

**Comment by nrpt-m** [comment]
> @MaxIhlenfeldt @rakuco Have completed the builds & testing in dunfell branch for all these below systems and chromium worked well in all these systems.
> 
> * chromium-ozone-wayland: qemux86-64
> * chromium-x11: qemux86-64, qemuarm, qemuarm64, raspberrypi4-64**
> 
> raspberrypi4-64**:- Have observed again the illegal instruction error with chromium-119 as well. Have attached the console logs. [chromium-119-rpi4-dunfell-console-logs.txt](https://github.com/OSSystems/meta-browser/files/13394825/chromium-119-rpi4-dunfell-console-logs.txt)
> 
> Coredump file at: https://tempsend.com/gxmzu Chromium-bin file at: https://tempsend.com/grcuz

@MaxIhlenfeldt , Could you please check these details about illegal instruction error.

**Comment by marex** [comment]
> @marex please look through the existing issues if this is already known (#711 sounds like it might be related?), and if not file a new issue, as this isn't related to this PR.

@MaxIhlenfeldt right, #711 was open for some 10 releases now and it seems there is no fix ? Is there any interest in fixing that problem ?

**Comment by TheNathan0** [comment]
Last I checked surrounding #711, using Google's Wayland fork supposedly *should've* fixed this but from my experience, it only resulted in a different error that I never looked further into.  I'm no expert at this so I hadn't looked much into it ever since I had failed to get Chromium starting with full GPU acceleration (by means of using flags: --in-process-gpu and --use-gl=egl).

It seems like x86-64 Arch Linux folks have gotten native EGL (no ANGLE abstraction layer) + native Ozone Wayland working on Chromium with Google's Wayland fork (See: [https://aur.archlinux.org/packages/chromium-wayland-vaapi](https://aur.archlinux.org/packages/chromium-wayland-vaapi) and some patching.  I'm not sure if this is going to help much, but I figured I'd put it just here in case someone interested might need it to figure out how to fix #711.  I'm going to assume that X11 is unaffected?

**Comment by MaxIhlenfeldt** [comment]
> @MaxIhlenfeldt right, #711 was open for some 10 releases now and it seems there is no fix ? Is there any interest in fixing that problem ?

I don't have that hardware and so can't do much about the issue, not sure if anyone else can work on it. Please use that issue to further discuss it instead of this PR.

**Pull request merged**
