### PR TITLE
chromium: Update to 72.0.3626.109.

### PR DESCRIPTION
**Pull request by rakuco**
Release announcement:
https://chromereleases.googleblog.com/2019/02/stable-channel-update-for-desktop_13.html

chromium-x11 was test-built on:
* rocko, GCC 7 and MACHINE="qemuarm64"
* sumo, GCC 7, MACHINE="raspberrypi3" and TOOLCHAIN_pn-chromium-x11="clang"
* thud, GCC 8, MACHINE="intel-core-i7-64" and MACHINE="intel-core2-32"

chromium-ozone-wayland was test-built on:
* thud, GCC 8, MACHINE="qemuarm64"

### CODE REVIEW

**Comment by rakuco** [comment]
AFAIK @msisov is testing chromium-ozone-wayland in more setups

**Comment by otavio** [comment]
I am good in merging this as far @kraj  and @msisov are too.

**Comment by msisov** [comment]
Looks good as well and I still need to verify it. But as long as X11 builds, ozone/Wayland must also build without any problems.

**Comment by msisov** [comment]
Verified with * Yocto sumo, GCC 7 and MACHINE="raspberrypi3"

**Pull request merged**
