### PR TITLE
chromium: Update to 129.0.6668.70

### LINKED ISSUE #837: Update to Chromium 129
Release notes:
* https://chromereleases.googleblog.com/2024/09/stable-channel-update-for-desktop_17.html
* https://chromereleases.googleblog.com/2024/09/stable-channel-update-for-desktop_24.html

### PR DESCRIPTION
**Pull request by MaxIhlenfeldt**
Fixes #837.

Release notes:
    https://chromereleases.googleblog.com/2024/09/stable-channel-update-for-desktop_17.html
    https://chromereleases.googleblog.com/2024/09/stable-channel-update-for-desktop_24.html

Build and patch changes:
------------------------

Drop one backported patch that is included upstream now.

Rebase remaining patches.

License changes:
----------------

Added licenses:
  * third_party/android_deps/libs/com_google_android_gms_play_services_identity_credentials/LICENSE
  - https://chromium-review.googlesource.com/c/chromium/src/+/5766672

  * third_party/fast_float/src/LICENSE-MIT
  - https://chromium-review.googlesource.com/c/chromium/src/+/5743598

Removed licenses:
  * ios/components/third_party/compiler-rt/LICENSE.TXT
  - https://chromium-review.googlesource.com/c/chromium/src/+/5767039

  * third_party/android_deps/libs/org_jetbrains_kotlin_kotlin_stdlib_jdk7/LICENSE, third_party/android_deps/libs/org_jetbrains_kotlin_kotlin_stdlib_jdk8/LICENSE
  - https://chromium-review.googlesource.com/c/chromium/src/+/5786197

  * third_party/catapult/third_party/html5lib-python/LICENSE
  - https://chromium-review.googlesource.com/c/catapult/+/5768072

  * third_party/libudev/LICENSE
  - https://chromium-review.googlesource.com/c/chromium/src/+/5738848

  * third_party/sudden_motion_sensor/LICENSE
  - https://chromium-review.googlesource.com/c/chromium/src/+/5734364

Updated licenses:
  * third_party/android_deps/libs/com_google_android_gms_play_services_base/LICENSE, third_party/android_deps/libs/com_google_android_gms_play_services_basement/LICENSE, third_party/android_deps/libs/com_google_android_gms_play_services_tasks/LICENSE
  - https://chromium-review.googlesource.com/c/chromium/src/+/5766672

Test-built (big thanks to @SoumyaWind):
---------------------------------------

* chromium-ozone-wayland:
 - master, clang,    MACHINE=qemux86-64
 - scarthgap, clang, MACHINE=qemuarm64, qemux86-64

* chromium-x11:
 - master, clang,    MACHINE=qemuarm, qemuarm64, qemux86-64, raspberrypi4-64
 - scarthgap, clang, MACHINE=qemuarm, qemuarm64, qemux86-64, raspberrypi4-64

### CODE REVIEW

**Comment by MaxIhlenfeldt** [comment]
@SoumyaWind testing would be greatly appreciated!

Note that I still see a similar error to https://github.com/OSSystems/meta-browser/pull/828#issuecomment-2273176913 and https://github.com/OSSystems/meta-browser/pull/832#issuecomment-2309837530 for my master qemuarm build.

**Review by rakuco — APPROVED** [review]
lgtm!

**Comment by SoumyaWind** [comment]
@MaxIhlenfeldt sure, I will start testing.

**Comment by neenareddi** [comment]
Hi @MaxIhlenfeldt 
When is this PR expected to merge into master?

**Comment by MaxIhlenfeldt** [comment]
> When is this PR expected to merge into master?

@neenareddi if nothing unexpected comes up during testing I'd estimate either the end of this weak or early next week. You can also always try it out yourself even if it hasn't been merged yet by using the `129.0.6668.70` branch of my fork at https://github.com/MaxIhlenfeldt/meta-browser.

**Comment by SoumyaWind** [comment]
@MaxIhlenfeldt, I have completed the testing for below configuration for Poky master with latest changes. Here are the results for your reference:

1. **chromium-x11 on qemux86-64 target:** Compiled successfully without any build issues. Verified chromium version using qemux86-64 emulator
2. **chromium-x11 on qemuarm target:** Without debug configuration, encountered the following error during build
>| arm-poky-linux-gnueabi-ld.lld: error: output file too large: 6851469836 bytes
>| section sizes:
>| .interp 25
>| .note.ABI-tag 32
>| .note.crashpad.info 28
>| .note.gnu.build-id 36
>| .dynsym 24976
>| .gnu.version 3122
>| .gnu.version_r 1040
>| .gnu.hash 372
>| .dynstr 35193
>| .rel.dyn 7029272
>| .ARM.exidx 8264
>| .rel.plt 11496
>| .rodata 14390013
>| .ARM.extab 11604
>| .eh_frame_hdr 12
>| .eh_frame 4
>| .text 143397216
>| .init 28
>| .fini 8
>| malloc_hook 500
>| .plt 23024
>| .tdata 168
>| .tbss 2972
>| .fini_array 4
>| .init_array 8
>| .data.rel.ro 4814168
>| .dynamic 472
>| .got 54080
>| .got.plt 5760
>| .relro_padding 336
>| .data 389872
>| .tm_clone_table 0
>| .bss 1557036
>| .comment 133
>| .ARM.attributes 59
>| .debug_aranges 264
>| .debug_info 3631417130
>| .debug_abbrev 140453648
>| .debug_line 275980532
>| .debug_str 1378849151
>| .debug_line_str 4053488
>| .debug_rnglists 152236070
>| .debug_loclists 325842467
>| .debug_str_offsets 585318600
>| .debug_addr 37504760
>| .debug_frame 21890472
>| .symtab 31458736
>| .shstrtab 545
>| .strtab 96259937
>|
>| arm-poky-linux-gnueabi-clang++: error: linker command failed with exit code 1 (use -v to see invocation)
>| ninja: build stopped: subcommand failed.

With GN configuration - is_debug=true, is_official_build=false, symbol_level=2 and with the dependencies:

- DISTRO_FEATURES with usrmerge and systemd
- VIRTUAL-RUNTIME_init_manager to systemd
- systemd and systemd-dev in IMAGE_INSTALL

The build was successful for qemuarm, and I was able to verify chromium version using qemuarm emulator
3. **chromium-x11 on qemuarm64 target:** Compiled successfully without build issues. Verified chromium version using qemuarm64 emulator
4. **chromium-x11 on raspberrypi4-64 target:** Compiled successfully without any build issues. I could not test on actual hardware due to unavailability.
5. **chromium-ozone-wayland on qemux86-64 target**: Compiled successfully without any build issues, verified chromium version using qemux86-64 emulator

**Comment by SoumyaWind** [comment]
Also, I have completed testing with the following configurations for poky scarthgap with the latest changes. Here are the results for your reference:

1. **chromium-x11 on qemux86-64 target:** Compiled successfully without any build issues, verified chromium version using the qemux86-64 emulator.
2. **chromium-x11 on qemuarm target:** Compiled successfully without any build issues, verified chromium version using the qemuarm emulator.
3. **chromium-x11 on qemuarm64 target:** Compiled successfully without any build issues, verified chromium version using the qemuarm64 emulator.
4. **chromium-x11 on raspberrypi4-64 target:** Compiled successfully without any build issues. I could not test on actual hardware due to unavailability.
5. **chromium-ozone-wayland on qemux86-64 target:** Compiled successfully without any build issues, verified chromium version using the qemux86-64 emulator.

**Comment by MaxIhlenfeldt** [comment]
Great, thanks!

**Pull request merged**
