### PR TITLE
chromium: Update to 128.0.6613.84

### LINKED ISSUE #831: Update to Chromium 128
Release notes:
* https://chromereleases.googleblog.com/2024/08/stable-channel-update-for-desktop_21.html

### PR DESCRIPTION
**Pull request by MaxIhlenfeldt**
Fixes #831.

Release notes:
    https://chromereleases.googleblog.com/2024/08/stable-channel-update-for-desktop_21.html

Build and patch changes:
------------------------

Drop 0012-m127-side_panel-Add-missing-deps.patch as m128 contains the proper fix for the issue this patch was working around.

Rebase remaining patches.

License changes:
----------------

Added licenses:
  * third_party/devtools-frontend/src/front_end/third_party/puppeteer/third_party/parsel/LICENSE
  - https://chromium-review.googlesource.com/c/devtools/devtools-frontend/+/5630499

Removed licenses:
  * third_party/catapult/third_party/polymer2/LICENSE.polymer
  - https://chromium-review.googlesource.com/c/catapult/+/5670761

  * third_party/setupdesign/LICENSE
  - https://chromium-review.googlesource.com/c/chromium/src/+/5659916

Updated licenses:
  * third_party/perfetto/LICENSE
  - https://android.googlesource.com/platform/external/perfetto/+/917165dd

Test-built (big thanks to @SoumyaWind):
---------------------------------------

* chromium-ozone-wayland:
 - master, clang,    MACHINE=qemux86-64
 - scarthgap, clang, MACHINE=qemuarm64, qemux86-64

* chromium-x11:
 - master, clang,    MACHINE=qemuarm, qemuarm64, qemux86-64, raspberrypi4-64
 - scarthgap, clang, MACHINE=qemuarm, qemuarm64, qemux86-64, raspberrypi4-64

### CODE REVIEW

**Comment by MaxIhlenfeldt** [comment]
@SoumyaWind testing would be greatly appreciated!

Note that I still see a similar error to https://github.com/OSSystems/meta-browser/pull/828#issuecomment-2273176913 for my master qemuarm build:
```
"python3" "../../build/toolchain/gcc_link_wrapper.py" --output="./chrome" -- arm-oe-linux-gnueabi-clang++ -target arm-oe-linux-gnueabi   -mfpu=neon -mfloat-abi=hard -mcpu=cortex-a15 -mlittle-endian -Qunused-arguments -D_TIME_BITS=64 -D_FILE_OFFSET_BITS=64 --sysroot=/home/gitlab-runner/yocto-chromium/builds/ci-chromium-x11-qemuarm-master/tmp-glibc/work/cortexa15t2hf-neon-oe-linux-gnueabi/chromium-x11/128.0.6613.84/recipe-sysroot -Wl,--version-script=../../build/linux/chrome.map -fuse-ld=lld -Wl,--fatal-warnings -Wl,--build-id=sha1 -fPIC -Wl,-z,noexecstack -Wl,-z,relro -Wl,-z,now -Wl,--icf=all -Wl,--color-diagnostics -Wl,-mllvm,-instcombine-lower-dbg-declare=0 -Wl,--thinlto-cache-dir=thinlto-cache -Wl,--thinlto-cache-policy=cache_size=10\%:cache_size_bytes=40g:cache_size_files=100000 -flto=thin -Wl,--thinlto-jobs=all -Wl,-mllvm,-import-instr-limit=30 -Wl,-mllvm,-disable-auto-upgrade-debug-info -Wl,-mllvm,-inlinehint-threshold=360 -fwhole-program-vtables -march=armv7-a -Wl,--undefined-version -Wl,--no-call-graph-profile-sort -Wl,-O2 -Wl,--gc-sections -Wl,-z,defs -Wl,--as-needed -rdynamic -pie -Wl,--disable-new-dtags -Wl,--lto-O2 prebuilt_rustc_sysroot/lib/rustlib/armv7-oe-linux-gnueabihf/lib/libstd.rlib prebuilt_rustc_sysroot/lib/rustlib/armv7-oe-linux-gnueabihf/lib/liballoc.rlib prebuilt_rustc_sysroot/lib/rustlib/armv7-oe-linux-gnueabihf/lib/libcfg_if.rlib prebuilt_rustc_sysroot/lib/rustlib/armv7-oe-linux-gnueabihf/lib/libcompiler_builtins.rlib prebuilt_rustc_sysroot/lib/rustlib/armv7-oe-linux-gnueabihf/lib/libcore.rlib prebuilt_rustc_sysroot/lib/rustlib/armv7-oe-linux-gnueabihf/lib/libgetopts.rlib prebuilt_rustc_sysroot/lib/rustlib/armv7-oe-linux-gnueabihf/lib/libhashbrown.rlib prebuilt_rustc_sysroot/lib/rustlib/armv7-oe-linux-gnueabihf/lib/libpanic_abort.rlib prebuilt_rustc_sysroot/lib/rustlib/armv7-oe-linux-gnueabihf/lib/libpanic_unwind.rlib prebuilt_rustc_sysroot/lib/rustlib/armv7-oe-linux-gnueabihf/lib/librustc_demangle.rlib prebuilt_rustc_sysroot/lib/rustlib/armv7-oe-linux-gnueabihf/lib/libstd_detect.rlib prebuilt_rustc_sysroot/lib/rustlib/armv7-oe-linux-gnueabihf/lib/libtest.rlib prebuilt_rustc_sysroot/lib/rustlib/armv7-oe-linux-gnueabihf/lib/libunicode_width.rlib prebuilt_rustc_sysroot/lib/rustlib/armv7-oe-linux-gnueabihf/lib/libunwind.rlib prebuilt_rustc_sysroot/lib/rustlib/armv7-oe-linux-gnueabihf/lib/libaddr2line.rlib prebuilt_rustc_sysroot/lib/rustlib/armv7-oe-linux-gnueabihf/lib/libadler.rlib prebuilt_rustc_sysroot/lib/rustlib/armv7-oe-linux-gnueabihf/lib/libgimli.rlib prebuilt_rustc_sysroot/lib/rustlib/armv7-oe-linux-gnueabihf/lib/liblibc.rlib prebuilt_rustc_sysroot/lib/rustlib/armv7-oe-linux-gnueabihf/lib/libmemchr.rlib prebuilt_rustc_sysroot/lib/rustlib/armv7-oe-linux-gnueabihf/lib/libminiz_oxide.rlib prebuilt_rustc_sysroot/lib/rustlib/armv7-oe-linux-gnueabihf/lib/libobject.rlib -Wl,-O1 -Wl,--hash-style=gnu -Wl,--as-needed   -fmacro-prefix-map=/home/gitlab-runner/yocto-chromium/builds/ci-chromium-x11-qemuarm-master/tmp-glibc/work/cortexa15t2hf-neon-oe-linux-gnueabi/chromium-x11/128.0.6613.84/chromium-128.0.6613.84=/usr/src/debug/chromium-x11/128.0.6613.84  -fdebug-prefix-map=/home/gitlab-runner/yocto-chromium/builds/ci-chromium-x11-qemuarm-master/tmp-glibc/work/cortexa15t2hf-neon-oe-linux-gnueabi/chromium-x11/128.0.6613.84/chromium-128.0.6613.84=/usr/src/debug/chromium-x11/128.0.6613.84  -fmacro-prefix-map=/home/gitlab-runner/yocto-chromium/builds/ci-chromium-x11-qemuarm-master/tmp-glibc/work/cortexa15t2hf-neon-oe-linux-gnueabi/chromium-x11/128.0.6613.84/chromium-128.0.6613.84/out/Release=/usr/src/debug/chromium-x11/128.0.6613.84  -fdebug-prefix-map=/home/gitlab-runner/yocto-chromium/builds/ci-chromium-x11-qemuarm-master/tmp-glibc/work/cortexa15t2hf-neon-oe-linux-gnueabi/chromium-x11/128.0.6613.84/chromium-128.0.6613.84/out/Release=/usr/src/debug/chromium-x11/128.0.6613.84  -fdebug-prefix-map=/home/gitlab-runner/yocto-chromium/builds/ci-chromium-x11-qemuarm-master/tmp-glibc/work/cortexa15t2hf-neon-oe-linux-gnueabi/chromium-x11/128.0.6613.84/recipe-sysroot=  -fmacro-prefix-map=/home/gitlab-runner/yocto-chromium/builds/ci-chromium-x11-qemuarm-master/tmp-glibc/work/cortexa15t2hf-neon-oe-linux-gnueabi/chromium-x11/128.0.6613.84/recipe-sysroot=  -fdebug-prefix-map=/home/gitlab-runner/yocto-chromium/builds/ci-chromium-x11-qemuarm-master/tmp-glibc/work/cortexa15t2hf-neon-oe-linux-gnueabi/chromium-x11/128.0.6613.84/recipe-sysroot-native=   -stdlib=libc++ -o "./chrome" -Wl,--start-group @"./chrome.rsp" -Wl,--end-group   /home/gitlab-runner/yocto-chromium/builds/ci-chromium-x11-qemuarm-master/tmp-glibc/work/cortexa15t2hf-neon-oe-linux-gnueabi/chromium-x11/128.0.6613.84/recipe-sysroot-native/usr/lib/clang/latest/lib/linux/libclang_rt.builtins-armhf.a -latomic -ldl -lpthread -lrt -lgmodule-2.0 -lgobject-2.0 -lgthread-2.0 -lglib-2.0 -lsmime3 -lnss3 -lsoftokn3 -lnssutil3 -lplds4 -lplc4 -lnspr4 -ldbus-1 -latk-1.0 -latk-bridge-2.0 -lgio-2.0 -lresolv -lexpat -ljpeg -luuid -ldrm -lxcb -lxkbcommon -latspi -lX11 -lXcomposite -lXdamage -lXext -lXfixes -lXrender -lXrandr -lXtst -lgbm -lXi -lpci -lpangocairo-1.0 -lpango-1.0 -lharfbuzz -lcairo -lasound -lFLAC -lm -lz -lxslt -lxml2 -lxshmfence -Wl,--start-group obj/third_party/rust/cxx/v1/lib/libcxx_lib.rlib obj/third_party/rust/serde_json_lenient/v0_2/wrapper/libthird_uparty_srust_sserde_ujson_ulenient_sv0_u2_swrapper_cwrapper.rlib obj/third_party/rust/serde/v1/lib/libserde_lib.rlib obj/third_party/rust/serde_json_lenient/v0_2/lib/libserde_json_lenient_lib.rlib obj/third_party/rust/itoa/v1/lib/libitoa_lib.rlib obj/third_party/rust/ryu/v1/lib/libryu_lib.rlib obj/build/rust/chromium_prelude/libchromium.rlib obj/skia/libskia_cbridge_urust_uside.rlib obj/third_party/rust/font_types/v0_5/lib/libfont_types_lib.rlib obj/third_party/rust/bytemuck/v1/lib/libbytemuck_lib.rlib obj/third_party/rust/read_fonts/v0_19/lib/libread_fonts_lib.rlib obj/third_party/rust/skrifa/v0_19/lib/libskrifa_lib.rlib obj/third_party/blink/common/rust_crash/libthird_uparty_sblink_scommon_srust_ucrash_crs.rlib obj/components/qr_code_generator/libcomponents_sqr_ucode_ugenerator_cqr_ucode_ugenerator_uffi_uglue.rlib obj/third_party/rust/qr_code/v2/lib/libqr_code_lib.rlib -Wl,--end-group
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
terminate called recursively
arm-oe-linux-gnueabi-clang++: error: unable to execute command: Aborted
arm-oe-linux-gnueabi-clang++: error: linker command failed due to signal (use -v to see invocation)
```

**Comment by SoumyaWind** [comment]
@MaxIhlenfeldt sure, I will start testing.

**Comment by SoumyaWind** [comment]
@MaxIhlenfeldt, I have completed the testing for below configuration for Poky master with latest changes. Here are the results for your reference:

1. **chromium-x11 on qemux86-64 target**: compiled successfully without any build issues. Verified chromium version using qemux86-64 emulator

2. **chromium-x11 on qemuarm target**: Without debug configuration, encountered the following error during build
>| arm-poky-linux-gnueabi-ld.lld: error: output file too large: 6852023460 bytes
>| section sizes:
>| .interp 25
>| .note.ABI-tag 32
>| .note.crashpad.info 28
>| .note.gnu.build-id 36
>| .dynsym 24496
>| .gnu.version 3062
>| .gnu.version_r 1008
>| .gnu.hash 372
>| .dynstr 34237
>| .rel.dyn 6898096
>| .ARM.exidx 8320
>| .rel.plt 11272
>| .rodata 14347106
>| .ARM.extab 11644
>| .eh_frame_hdr 12
>| .eh_frame 4
>| .text 142825292
>| .init 28
>| .fini 8
>| malloc_hook 496
>| .plt 22576
>| .tdata 168
>| .tbss 2972
>| .fini_array 4
>| .init_array 8
>| .data.rel.ro 4732952
>| .dynamic 464
>| .got 53392
>| .got.plt 5648
>| .relro_padding 3064
>| .data 387192
>| .tm_clone_table 0
>| .bss 1552812
>| .comment 112
>| .ARM.attributes 59
>| .debug_aranges 264
>| .debug_info 3621093166
>| .debug_abbrev 139319359
>| .debug_line 272881816
>| .debug_str 1365498960
>| .debug_line_str 4031001
>| .debug_rnglists 156175408
>| .debug_loclists 353268960
>| .debug_frame 21744260
>| .debug_str_offsets 581250940
>| .debug_addr 37808532
>| .symtab 31153136
>| .shstrtab 545
>| .strtab 98423165
>|
>| arm-poky-linux-gnueabi-clang++: error: linker command failed with exit code 1 (use -v to see invocation)
>| ninja: build stopped: subcommand failed.

With GN configuration - is_debug=true, is_official_build=false, symbol_level=2 and with the dependencies:
- DISTRO_FEATURES with usrmerge and systemd
- VIRTUAL-RUNTIME_init_manager to systemd
- systemd and systemd-dev in IMAGE_INSTALL

The build was successful for qemuarm, and I was able to verify chromium version using qemuarm emulator

3. **chromium-x11 on qemuarm64 target**: compiled successfully without build issues. Verified chromium version using qemuarm64 emulator

4. **chromium-x11 on raspberrypi4-64 target**: Encountered a build error 
>ERROR: No recipes in default available for:
>  /meta-raspberrypi/recipes-graphics/mesa/mesa-gl_%.bbappend
>  /meta-raspberrypi/recipes-graphics/mesa/mesa_%.bbappend

This error was caused by a commit - https://git.openembedded.org/openembedded-core/commit/?id=f5cfb3e23603cefb2f3f6bfe776afaedefd10808)
After reverting this commit locally, the build was successful without any issues. I could not test on actual hardware due to unavailability.

5. **chromium-ozone-wayland on qemux86-64 target**: compiled successfully without any build issues, verified chromium version using qemux86-64 emulator

**Comment by SoumyaWind** [comment]
Also, I have completed testing with the following configurations for poky scarthgap with the latest changes. Here are the results for your reference:

1. **chromium-x11 on qemux86-64 target**: Compiled successfully without any build issues, verified chromium version using the qemux86-64 emulator.

2. **chromium-x11 on qemuarm target**: Compiled successfully without any build issues, verified chromium version using the qemuarm emulator.

3. **chromium-x11 on qemuarm64 target**: Compiled successfully without any build issues, verified chromium version using the qemuarm64 emulator.

4. **chromium-x11 on raspberrypi4-64 target**: Compiled successfully without any build issues. I could not test on actual hardware due to unavailability.

5. **chromium-ozone-wayland on qemux86-64 target**: Compiled successfully without any build issues, verified chromium version using the qemux86-64 emulator.

**Comment by MaxIhlenfeldt** [comment]
@kraj can you please review?

**Review by rakuco — APPROVED** [review]
Oops, sorry for the delay, I've just come back from vacation. LGTM!

**Pull request merged**
