### PR TITLE
chromium: update all patches to have git header and musl patches to apply on 89.* version

### PR DESCRIPTION
**Pull request by shr-project**

### CODE REVIEW

**Comment by shr-project** [comment]
Depends on https://github.com/OSSystems/meta-browser/pull/477

**Review by kraj — APPROVED** [review]
this patch looks ok. Provided you rebased it after merging #477

**Comment by otavio** [comment]
I merged #477. Once this is rebased i can merge it.

**Comment by shr-project** [comment]
> I merged #477. Once this is rebased i can merge it.

You're too quick, I'm still build testing this one with musl enabled (and asked Khem to test it in runtime with musl as he probably has some useful image or that).

But I did check that all the patches do apply cleanly, so at least it doesn't make things worse :). In worst case more fixes for musl will be needed. I will report once the build is finished - later tonight or tomorrow.

BTW: the build time of chromium itself is almost double with hardknott (and latest meta-browser) compared with dunfell / zeus (meta-browser 5e58ff65facc27a3054a4d3f97d3329342d49afa / 1697014a05967ed54b294f3c4b5621df494d6551), not sure where all that extra time was spent yet (will publish more results in https://github.com/shr-project/test-oe-build-time soon).

**Comment by shr-project** [comment]
Rebased and build-tested OK with qemux86-64 with musl.

**Pull request merged**
