### PR TITLE
chromium: update to 105.0.5195.102

### LINKED ISSUE #660: Update to chromium 105.0.5195.52
https://chromereleases.googleblog.com/2022/08/stable-channel-update-for-desktop_16.html

Is anyone able to do this update ? I'm busy with other work and then on vacation until Oct 1st.

### PR DESCRIPTION
**Pull request by msisov**
```
Release notes -
https://chromereleases.googleblog.com/2022/09/stable-channel-update-for-desktop.html

License changes:
----------------

Added licenses:
  * third_party/crubit/LICENSE
  - https://chromium-review.googlesource.com/c/chromium/src/+/3756853

  * third_party/swift-toolchain/LICENSE
  - https://chromium-review.googlesource.com/c/chromium/src/+/3722369

Removed licenses: (none)

Updated licenses:
  * third_party/libevent/LICENSE
  * (The license library's folder was moved from //base to //third_party)
  - https://chromium-review.googlesource.com/c/chromium/src/+/3695888

Test-built:
-----------

* chromium-ozone-wayland:
 - master, clang,    MACHINE=qemux86-64, qemuarm64, qemuarm
 - kirkstone, clang, MACHINE=raspberrypi3

* chromium-x11
 - master, clang,    MACHINE=qemux86-64, qemuarm64, qemuarm
 - dunfell, clang**, MACHINE=raspberrypi3

** Please note that Chromium requires clang version to be >= 12.
For that, when on dunfell branch, use the meta-clang/clang12 branch.

Signed-off-by: Maksim Sisov <msisov@igalia.com>
```

Fixes #660

### CODE REVIEW

**Review by rakuco — APPROVED** [review]
lgtm!

@rwmacleod could you take a look at this and see if it works in your builds as well?

**Comment by kraj** [comment]
clang has been updated to 15.0.0 in meta-clang/master, it will be good to report back on testing with `master`  meta-clang as well.

**Comment by rwmacleod** [comment]
Both chromium-x11 and chromium-ozone-wayland build fine on master for qemux86-64 qemuarm64 qemuarm.
It runs fine on qemux86-64 under x11.  I'll build kirkstone next but since you've built rpi3 there, it's probably fine.

**Comment by kraj** [comment]
> Both chromium-x11 and chromium-ozone-wayland build fine on master for qemux86-64 qemuarm64 qemuarm. It runs fine on qemux86-64 under x11. I'll build kirkstone next but since you've built rpi3 there, it's probably fine.

phew, I was worried but great it works on first try :)

**Comment by msisov** [comment]
Do you have any other comments/suggestions? If not, I'll merge this today.

**Comment by rakuco** [comment]
Other than including the additional platforms and branches that @rwmacleod tested, no additional comments. Thanks for working on this update!

**Comment by rwmacleod** [comment]
For the record, both chromium-x11 and chromium-ozone-wayland build fine on **kirkstone** for qemux86-64 qemuarm64 qemuarm.  Thanks @msisov @kraj @rakuco .

**Pull request merged**
