### PR TITLE
chromium: update to 92.0.4515.107

### PR DESCRIPTION
**Pull request by msisov**
Stable release announcements since our latest update:
https://chromereleases.googleblog.com/2021/07/stable-channel-update-for-desktop_20.html

License changes
---------------
Added licenses:
  * third_party/android_deps/libs/org_jetbrains_annotations/LICENSE
  - Move jetbrains_annotations and ASM into android_deps
  - https://crrev.com/c/2034076

  * third_party/android_deps/libs/org_jetbrains_kotlin_kotlin_stdlib/LICENSE
  * third_party/android_deps/libs/org_jetbrains_kotlin_kotlin_stdlib_common/LICENSE
  - Add jetify-standalone to third_party
  - https://crrev.com/c/1992352

  * third_party/flex/LICENSE
  - 3pp: Add configurations for building "mig", and its dependency "flex"
  - https://crrev.com/c/2850333

  * third_party/material_web_components/LICENSE
  - Add Material Web Components to third_party/
  - https://crrev.com/c/2771528

Removed licenses:
  * third_party/tint/LICENSE
  - Remove //third_party/tint
  - https://crrev.com/c/2821810

Updated licenses:
  * third_party/libjpeg_turbo/LICENSE.md
  - Roll src/third_party/libjpeg_turbo/ 24e310554..b7bef8c05 (2 commits)
  - https://crrev.com/c/2879874

  * third_party/vulkan-deps/vulkan-validation-layers/src/LICENSE.txt
  - Publish DEPS for 92.0.4515.107
  - no link.

Test-built with:
* chromium-x11
  * dunfell, clang, MACHINE="intel-core2-32"
  * dunfell, clang, MACHINE="intel-corei7-64"
  * dunfell, clang, MACHINE="raspberrypi3"
  * gatesgarth, MACHINE="raspberrypi3"

* chromium-ozone-wayland:
  * dunfell, clang, MACHINE="intel-corei7-64"
  * dunfell, clang, MACHINE="qemuarm64"
  * gatesgarth, clang, MACHINE="raspberrypi3"
  * dunfell, clang, MACHINE="m3ulcb"
  * hardknott, clang, MACHINE="raspebrrypi3"

Fixes: 526

### CODE REVIEW

**Comment by TonyTascioglu** [comment]
Hello, let me know if/when I should give this a test build

**Comment by msisov** [comment]
Testing with hardknott is on its way (bot is configured and is executing now). But I don't expect any problems there. If any, I'll send a separate PR if there are failures to be fixed.

**Comment by msisov** [comment]
> Hello, let me know if/when I should give this a test build

You can already. Thx.

**Comment by msisov** [comment]
hardknott also passed. @rakuco please review.

**Comment by msisov** [comment]
Looks like @rakuco is OOO. @otavio can you please review?

**Comment by TonyTascioglu** [comment]
fwiw, here are the results from my tests:
- build worked fine on poky with hardknott branch for all layers
- chromium works as expected in qemu, but network access is still broken on the raspberry pi
- build does not work on poky with master branch, probably due to stricter compiler checks

**Comment by r1mikey** [comment]
Lightly tested on Hardknott, meta-intel-based BSP, Kiosk mode.

* Tested touch, audio, 3D, CSS transition performance.
* Tested video playback

No regressions found from 91.x.

**Review by otavio — APPROVED** [review]

**Comment by otavio** [comment]
@msisov sorry for the late response. I am merging it now.

**Pull request merged**
