### PR TITLE
layer.conf: Add honister to LAYERSERIES_COMPAT

### PR DESCRIPTION
**Pull request by ckalluri73**
Add hoister to LAYERSERIES_COMPAT

Signed-off-by: Sai Hari Chandana Kalluri <chandana.kalluri@xilinx.com>

### CODE REVIEW

**Comment by shr-project** [comment]
There is no point in adding it without changing the overrides syntax as done in https://github.com/OSSystems/meta-browser/pull/530

**Comment by kraj** [comment]
> There is no point in adding it without changing the overrides syntax as done in #530

I think it will be needed regardless if override change or not towards the release. So perhaps it can be applied independent of override changes.

**Comment by shr-project** [comment]
It doesn't parse with current honister, marking it as compatible with honister without override changes to make it compatible with honister is wrong.

**Comment by otavio** [comment]
I agree with @shr-project here. We ought to put it as part of #530 so we handle it together.

@ckalluri73 as this is already included in #530 I'll close this PR.

**Pull request closed without merging**
