### PR TITLE
chromium: Update to 124.0.6367.207

### LINKED ISSUE #817: Update to Chromium 124
Release notes:
* https://chromereleases.googleblog.com/2024/04/stable-channel-update-for-desktop_16.html
* https://chromereleases.googleblog.com/2024/04/stable-channel-update-for-desktop_24.html
* https://chromereleases.googleblog.com/2024/05/stable-channel-update-for-desktop.html
* https://chromereleases.googleblog.com/2024/04/stable-channel-update-for-desktop_30.html
* https://chromereleases.googleblog.com/2024/05/stable-channel-update-for-desktop_7.html
* https://chromereleases.googleblog.com/2024/05/stable-channel-update-for-desktop_9.html
* https://chromereleases.googleblog.com/2024/05/stable-channel-update-for-desktop_13.html

### PR DESCRIPTION
**Pull request by MaxIhlenfeldt**
Fixes #817.

Release notes:
    https://chromereleases.googleblog.com/2024/04/stable-channel-update-for-desktop_16.html
    https://chromereleases.googleblog.com/2024/04/stable-channel-update-for-desktop_24.html
    https://chromereleases.googleblog.com/2024/05/stable-channel-update-for-desktop.html
    https://chromereleases.googleblog.com/2024/04/stable-channel-update-for-desktop_30.html
    https://chromereleases.googleblog.com/2024/05/stable-channel-update-for-desktop_7.html
    https://chromereleases.googleblog.com/2024/05/stable-channel-update-for-desktop_9.html
    https://chromereleases.googleblog.com/2024/05/stable-channel-update-for-desktop_13.html

Build and patch changes:
------------------------

Rebase patches.

License changes:
----------------

Added licenses:
  * third_party/devtools-frontend/src/front_end/third_party/puppeteer/third_party/mitt/LICENSE,
    third_party/devtools-frontend/src/front_end/third_party/puppeteer/third_party/rxjs/LICENSE
  - https://chromium-review.googlesource.com/c/devtools/devtools-frontend/+/5349136

  * third_party/protobuf-javascript/LICENSE
  - https://chromium-review.googlesource.com/c/chromium/src/+/5365789

Removed licenses:
  * third_party/catapult/third_party/WebOb/docs/license.txt
  - https://chromium-review.googlesource.com/c/catapult/+/5324206

  * v8/LICENSE.fdlibm, v8/LICENSE.strongtalk
  - Most likely wrongly removed due to https://crrev.com/c/5375144. See
    https://crbug.com/342197912.

Updated licenses:
  * third_party/ffmpeg/CREDITS.chromium
  - https://chromium-review.googlesource.com/c/chromium/third_party/ffmpeg/+/5315059

  * third_party/selenium-atoms/LICENSE.sizzle
  - https://chromium-review.googlesource.com/c/chromium/src/+/5339957

Test-built (big thanks to @rjanani-p):
--------------------------------------

* chromium-ozone-wayland:
 - master, clang,    MACHINE=qemux86-64
 - scarthgap, clang, MACHINE=qemuarm64, qemux86-64

* chromium-x11:
 - master, clang,    MACHINE=qemuarm, qemuarm64, qemux86-64, raspberrypi4-64
 - scarthgap, clang, MACHINE=qemuarm, qemuarm64, qemux86-64, raspberrypi4-64

### CODE REVIEW

**Comment by MaxIhlenfeldt** [comment]
@rjanani-p as always, testing would be greatly appreciated!

Will add the Licenses section soon, I uploaded the PR already so you can start testing.

**Review by rakuco — APPROVED** [review]
I'm surprised by how small this PR looks compared to the previous ones!

**Comment by rjanani-p** [comment]
> @rjanani-p as always, testing would be greatly appreciated!
> 
> Will add the Licenses section soon, I uploaded the PR already so you can start testing.

@MaxIhlenfeldt , I tried to start testing for poky master ,but facing below Errors while adding meta-openembedded dependent layer to the chromium build using "bitbake-layers add-layer $chromium/chromium_ver_builds/repos/meta-openembedded/meta-*" command, 

ERROR:$/chromium/chromium_ver_builds/repos/meta-openembedded/meta-initramfs/recipes-core/initrdscripts/initramfs-debug_1.0.bb: Using S = ${WORKDIR} is no longer supported
ERROR: $/chromium/chromium_ver_builds/repos/meta-openembedded/meta-oe/recipes-support/nmon/nmon_16m.bb: Using S = ${WORKDIR} is no longer supported
ERROR: Parsing halted due to errors, see error messages above                                                  | ETA:  0:00:36
ERROR: $/chromium/chromium_ver_builds/repos/meta-openembedded/meta-oe/recipes-graphics/ttf-fonts/ttf-lklug_0.6-14.20090803cvs.fc24.bb: Using S = ${WORKDIR} is no longer supported
ERROR:$/chromium/chromium_ver_builds/repos/meta-openembedded/meta-initramfs/recipes-bsp/kexecboot/kexecboot-cfg_0.2.bb: Using S = ${WORKDIR} is no longer supported
ERROR: $/chromium/chromium_ver_builds/repos/meta-openembedded/meta-oe/recipes-bsp/lm_sensors/lmsensors-config_1.0.bb: Using S = ${WORKDIR} is no longer supported
ERROR:$/chromium/chromium_ver_builds/repos/meta-openembedded/meta-oe/recipes-support/pxaregs/pxaregs_1.14.bb: Using S = ${WORKDIR} is no longer supported
ERROR: $/chromium/chromium_ver_builds/repos/meta-openembedded/meta-oe/recipes-benchmark/linpack/linpack_1.0.bb: Using S = ${WORKDIR} is no longer supported
ERROR: $/chromium/chromium_ver_builds/repos/meta-openembedded/meta-oe/recipes-devtools/systemd/nativesdk-systemd-systemctl.bb: Using S = ${WORKDIR} is no longer supported
ERROR: $/chromium/chromium_ver_builds/repos/meta-openembedded/meta-oe/recipes-support/libjs/libjs-jquery_3.3.1.bb: Using S = ${WORKDIR} is no longer supported
ERROR: $/chromium/chromium_ver_builds/repos/meta-openembedded/meta-oe/recipes-benchmark/whetstone/whetstone_1.2.bb: Using S = ${WORKDIR} is no longer supported
ERROR:$/chromium/chromium_ver_builds/repos/meta-openembedded/meta-gnome/recipes-gnome/faenza-icon-theme/faenza-icon-theme_1.3.bb: Using S = ${WORKDIR} is no longer supported
ERROR: $/chromium/chromium_ver_builds/repos/meta-openembedded/meta-oe/recipes-core/proxy-libintl/proxy-libintl_20100902.bb: Using S = ${WORKDIR} is no longer supported
ERROR: $/chromium/chromium_ver_builds/repos/meta-openembedded/meta-oe/recipes-core/usleep/usleep_1.2.bb: Using S = ${WORKDIR} is no longer supported
ERROR:$/chromium/chromium_ver_builds/repos/meta-openembedded/meta-oe/recipes-test/testfloat/testfloat_3e.bb: Using S = ${WORKDIR} is no longer supported
ERROR: $/chromium/chromium_ver_builds/repos/meta-openembedded/meta-oe/recipes-bsp/pointercal/pointercal_0.0.bb: Using S = ${WORKDIR} is no longer supported
ERROR:$/chromium/chromium_ver_builds/repos/meta-openembedded/meta-oe/recipes-graphics/ttf-fonts/ttf-google-fira.bb: Using S = ${WORKDIR} is no longer supported
WARNING: $/chromium/chromium_ver_builds/chromium_124_ver_testing/poky_master/meta/recipes-core/images/core-image-ptest.bb: Error during finalise of virtual:mcextend:libtimedate-perl:$/chromium/chromium_ver_builds/chromium_124_ver_testing/poky_master/meta/recipes-core/images/core-image-ptest.bb
WARNING:$/chromium/chromium_ver_builds/repos/meta-openembedded/meta-python/recipes-core/images/meta-python-image-ptest.bb: Error during finalise of virtual:mcextend:python3-parse-type:$/chromium/chromium_ver_builds/repos/meta-openembedded/meta-python/recipes-core/images/meta-python-image-ptest.bb



From the web, I have understood below commit going to resolve the issue,
**https://lore.kernel.org/openembedded-devel/20240515224900.232825-2-raj.khem@gmail.com/#r**

are you able to build the chromium-x11 for poky master? could you please share your inputs.

**Comment by rakuco** [comment]
> @rakuco if upstream confirms in the linked bug that these licenses were indeed wrongly removed, should we add them back to `LIC_FILES_CHKSUM` manually?

IMO, whatever makes your life easy. I'm fine with landing this PR as-is and, depending on the upstream bug's outcome, add them back manually (possibly with a backport of an eventual upstream fix).

> Also, I just realized we have lots of `third_party/android_deps` stuff in there... we could probably just ignore any path starting with that in our license script and drop them all?

I _think_ so. I've never looked too deeply into those directories and thought there could be a chance that they were included somewhere in the build (`chrome://credits` does list a bunch of Android libraries that probably aren't used on Linux too), but you're probably right.

**Comment by MaxIhlenfeldt** [comment]
> are you able to build the chromium-x11 for poky master? could you please share your inputs.

@rjanani-p I am, but that might be because I have a slightly different setup. I have a script that creates `bblayer.conf` manually, i.e. `meta-openembedded/meta-oe` is added to `BBLAYERS` without using `bitbake-layers add-layer`. There weren't any warnings or errors when running `bitbake chromium-x11`.

**Comment by MaxIhlenfeldt** [comment]
> I'm fine with landing this PR as-is and, depending on the upstream bug's outcome, add them back manually (possibly with a backport of an eventual upstream fix).

sgtm!

> I _think_ so. I've never looked too deeply into those directories and thought there could be a chance that they were included somewhere in the build (`chrome://credits` does list a bunch of Android libraries that probably aren't used on Linux too), but you're probably right.

I'll double-check and ask on the Chromium Slack if it's safe to assume stuff from `//third_party/android_deps` isn't used on Linux, and if yes will follow up with a PR once this one has been merged.

**Comment by rjanani-p** [comment]
> @rjanani-p as always, testing would be greatly appreciated!
> 
> Will add the Licenses section soon, I uploaded the PR already so you can start testing.

@MaxIhlenfeldt , I have completed the testing for below configuration for Poky master with latest changes, sharing the results for reference:

1.For chromium-x11 & qemux86-64 target: compiled successfully without build issues, able to check chromium version using qemux86-64 emulator

2.For chromium-x11 & qemuarm target: compiled successfully without build issues, to check chromium version using qemuarm emulator unable to check it due to curser / mouse is not working properly while operating with chromium browser

3.For chromium-x11 & qemuarm64 target: compiled successfully without build issues, able to check chromium version using qemuarm64 emulator

I will share the remaining test results once testing is completed. Thank you.

**Comment by darren-etheridge** [comment]
@MaxIhlenfeldt  - This Chromium 124 pull builds and runs on TI AARCH64 Linux wayland (Yocto Scarthgap) platforms with PowerVR GPU acceleration enabled and functional.   The GPU Patch that I mentioned for 123 is already incorporated into 124, so I dropped that one.  I'll keep testing and let you know I find anything.

**Comment by rjanani-p** [comment]
> @rjanani-p as always, testing would be greatly appreciated!
> 
> Will add the Licenses section soon, I uploaded the PR already so you can start testing.

@MaxIhlenfeldt , I have completed the testing for below configuration for Poky scarthgap branch with latest changes, sharing the results for reference:

1.For chromium-x11 & qemux86-64 target: compiled successfully without build issues, able to check chromium version using qemux86-64 emulator

2.For chromium-x11 & qemuarm target: compiled successfully without build issues, to check chromium version using qemuarm emulator unable to check it due to curser / mouse is not working properly while operating with chromium browser

I will share the remaining test results once testing is completed. Thank you.

**Comment by rjanani-p** [comment]
@MaxIhlenfeldt , I am trying to build chromium-x11 package for rasberrypi4-64 target for poky master branch. I am facing issue while adding meta-rasberrypi layer to chromium build. 
I am sharing Error for reference:
ERROR: No recipes in default available for:
  $/meta-raspberrypi/recipes-multimedia/gstreamer/gstreamer1.0-omx_%.bbappend

didn't get any issues while checking for poky scarthgap branch. 

Are you build the chromium-x11 package for rasberrypi-64 target for poky master branch?

**Comment by MaxIhlenfeldt** [comment]
Thanks @rjanani-p for all the testing! And also sorry for my late response, the last two weeks have been quite busy.

iiuc, it seems we're good to go? If so, I'll merge this PR later today or on Monday.

**Pull request merged**
