### PR TITLE
chromium: fix building with clang 10

### PR DESCRIPTION
**Pull request by MastaG**
Thanks @kraj  for the original patch.

### CODE REVIEW

**Comment by otavio** [comment]
All those looks good to go, I wonder if it did not break old versions.

@rakuco do you mind triggering a build with this?

**Comment by rakuco** [comment]
I'm launching a warrior-intel-corei7-64 to double-check. I still need to check those patches a bit more closely though, at least some of them look like libstdc++ fixes, not clang ones (especially since Chromium itself is always using a bleeding-edge clang version).

**Comment by MastaG** [comment]
Well I can speak for the missing includes that they're definitely required to build ozone-wayland for armv7.
I reported them here: https://github.com/OSSystems/meta-browser/issues/367

The other patches I can't review since I'm no C++ developer.

But I can verify that they do not break the build.

**Comment by otavio** [comment]
@kraj @rakuco ?

**Comment by kraj** [comment]
These patches have been working ok for me for few months

**Comment by MastaG** [comment]
I can only speak for 32bit arm on the OE master branches.
And I've only did a clang with ld-is-ldd build.
So I can't speak for other architectures, older branches or compiling with gcc.

**Pull request merged**
