### PR TITLE
Build native parts with clang, fix build with glibc 2.34

### PR DESCRIPTION
**Pull request by kraj**

### CODE REVIEW

**Comment by MastaG** [comment]
Thanks for this, works like a charm for armv7

**Comment by otavio** [comment]
@kraj can you rebase this on top of master?

**Comment by kraj** [comment]
@otavio done, this also contains @shr-project pull, since I needed to fix the recipes to consider runtime-llvm override and port the original patch to apply on top of chromium upgraded recipe that committed recently.

**Comment by otavio** [comment]
Good; please let us know when it is good to go.

**Comment by kraj** [comment]
this patchset is building fine with glibc 2.34/qemux86-64 on master now.

**Review by otavio — APPROVED** [review]

**Review by msisov — APPROVED** [review]

**Pull request merged**
