### PR TITLE
chromium: Update to 125.0.6422.141

### LINKED ISSUE #818: Update to Chromium 125
Release notes:
* https://chromereleases.googleblog.com/2024/05/stable-channel-update-for-desktop_15.html
* https://chromereleases.googleblog.com/2024/05/stable-channel-update-for-desktop_21.html
* https://chromereleases.googleblog.com/2024/05/stable-channel-update-for-desktop_23.html
* https://chromereleases.googleblog.com/2024/05/stable-channel-update-for-desktop_30.html

### PR DESCRIPTION
**Pull request by MaxIhlenfeldt**
Fixes #818.

Release notes:
    https://chromereleases.googleblog.com/2024/05/stable-channel-update-for-desktop_15.html
    https://chromereleases.googleblog.com/2024/05/stable-channel-update-for-desktop_21.html
    https://chromereleases.googleblog.com/2024/05/stable-channel-update-for-desktop_23.html
    https://chromereleases.googleblog.com/2024/05/stable-channel-update-for-desktop_30.html

Build and patch changes:
------------------------

Drop one backported patch that is included in upstream now.

Rebase remaining patches.

License changes:
----------------

Added licenses:
  * third_party/bidimapper/licenses/LICENSE.mitt, third_party/bidimapper/licenses/LICENSE.urlpattern_polyfill, third_party/bidimapper/licenses/LICENSE.zod
  - https://chromium-review.googlesource.com/c/chromium/src/+/5374914

  * third_party/lens_server_proto/LICENSE
  - https://chromium-review.googlesource.com/c/chromium/src/+/5394109

Removed licenses:
  * third_party/selenium-atoms/LICENSE.closure
  - https://chromium-review.googlesource.com/c/chromium/src/+/5424804

Updated licenses:
  * third_party/icu/LICENSE
  - https://chromium-review.googlesource.com/c/chromium/deps/icu/+/5397901

Test-built (big thanks to @rjanani-p):
--------------------------------------

* chromium-ozone-wayland:
 - master, clang,    MACHINE=qemux86-64
 - scarthgap, clang, MACHINE=qemuarm64, qemux86-64

* chromium-x11:
 - master, clang,    MACHINE=qemuarm, qemuarm64, qemux86-64, raspberrypi4-64
 - scarthgap, clang, MACHINE=qemuarm, qemuarm64, qemux86-64, raspberrypi4-64

### CODE REVIEW

**Comment by MaxIhlenfeldt** [comment]
@rjanani-p as always, testing would be greatly appreciated!

**Review by rakuco — APPROVED** [review]
lgtm!

**Comment by rjanani-p** [comment]
> @rjanani-p as always, testing would be greatly appreciated!

@MaxIhlenfeldt I will start testing. Thank you

**Comment by rjanani-p** [comment]
> @rjanani-p as always, testing would be greatly appreciated!

@MaxIhlenfeldt , I have completed the testing for below configuration for Poky master with latest changes, sharing the results for reference:

1.For chromium-x11 & qemux86-64 target: compiled successfully without build issues, able to check chromium version using qemux86-64 emulator

2.For chromium-x11 & qemuarm target: compiled successfully without build issues, to check chromium version using qemuarm emulator unable to check it due to curser / mouse is not working properly while operating with chromium browser

3.For chromium-x11 & qemuarm64 target: compiled successfully without build issues, able to check chromium version using qemuarm64 emulator
4. For chromium-ozone-wayland & qemux86-64 target: compiled successfully without build issues, able to check chromium version using qemux86-64 emulator
5. For chromium-x11 & raspberrypi4-64 target: compiled successfully without build issues, didn't check with hardware due to hardware unavailability.

I will start testing for poky scarthgap branch. Thank you.

**Comment by rjanani-p** [comment]
@MaxIhlenfeldt ,I have completed the testing with latest changes for Poky scarthgap branch for below configuration, sharing the results for reference:

1.For chromium-x11 & qemux86-64 target: compiled successfully without build issues, able to check chromium version using qemux86-64 emulator

2.For chromium-x11 & qemuarm target: compiled successfully without build issues, to check chromium version using qemuarm emulator unable to check it due to curser / mouse is not working properly while operating with chromium browser

3.For chromium-x11 & qemuarm64 target: compiled successfully without build issues, able to check chromium version using qemuarm64 emulator
4. For chromium-x11 & raspberrypi4-64 target: compiled successfully without build issues, didn't check with hardware due to hardware unavailability.
5. For chromium-ozone-wayland & qemux86-64 target: compiled successfully without build issues, able to check chromium version using qemux86-64 emulator

**Comment by MaxIhlenfeldt** [comment]
Thanks for testing!

**Pull request merged**
